aquasecurity/defsec

loader/rules.go
provider/github/actions.go
provider/github/github.go
rules/github/actions/no_plain_text_secrets.go
tests/loader_test.go

- check that the github action env secret hsa no plain text value

Add github action check

---

rules/azure/database/retention_period_set.go

Fixes https://github.com/aquasecurity/tfsec/issues/1240

Add support for setting retention period to 0/forever.

---

cidr/cidr.go
cidr/cidr_test.go

Fixes uint64 overflow when mask is 128bits

CIDR count fix

---

avd_docs/digitalocean/compute/AVD-DIG-0005/Terraform.md
avd_docs/digitalocean/compute/AVD-DIG-0005/docs.md
provider/digitalocean/compute/compute.go
rules/digitalocean/compute/kubernetes_surge_upgrades.go
rules/digitalocean/compute/kubernetes_surge_upgrades.tf.go

I'm not really sure about tests, but perhaps those are just added in `tfsec` ?

Add check to test for surge_upgrade in Kubernetes clusters

---

provider/azure/keyvault/keyvault.go
rules/azure/keyvault/no_purge.go
types/time_value.go

Add check for  soft delete retention days attribute to map old tfsec logic, see: https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/azure/keyvault/no_purge_rule.go#L49
Check for zero value of time type

Azure keyvault add check for soft delete retention days

---

provider/google/sql/sql.go

Refactor to simplify the adapter in tfsec and calm down the linter.

refactor google db instance struct

---

formatters/checkstyle.go
formatters/csv.go
formatters/default.go
formatters/factory.go
formatters/formatter.go
rules/flat.go
rules/result.go

Support optional grouping of results

---

rules/aws/ec2/enforce_http_token_imds_test.go
rules/aws/ec2/no_secrets_in_user_data_test.go

feat: Add unit tests for AWS EC2 rules

---

rules/aws/efs/enable_at_rest_encryption_test.go

feat: add unit tests for AWS EFS rules

---

rules/aws/eks/enable_control_plane_logging_test.go
rules/aws/eks/encrypt_secrets_test.go
rules/aws/eks/no_public_cluster_access_test.go
rules/aws/eks/no_public_cluster_access_to_cidr_test.go

feat: add tests for AWS EKS rules

---

provider/aws/autoscaling/autoscaling.go
provider/aws/ec2/instance.go
rules/aws/ec2/enable_at_rest_encryption.cf.go
rules/aws/ec2/enable_at_rest_encryption.go
rules/aws/ec2/enable_at_rest_encryption.tf.go
rules/aws/ec2/enable_at_rest_encryption_test.go

- fix: Fix issue with instances being counted in auto scaling
- fix: Change arg name

fix: correct autoscaling duplicates

---

rules/aws/documentdb/enable_log_export_test.go
rules/aws/documentdb/enable_storage_encryption_test.go
rules/aws/documentdb/encryption_customer_key_test.go

feat: add unit tests for AWS DocDB rules

---

rules/aws/kinesis/enable_in_transit_encryption_test.go

feat: add unit tests for AWS Kinesis rules

---

rules/aws/ssm/secret_use_customer_key_test.go

feat: add unit tests for AWS SSM rules

---

rules/aws/autoscaling/enable_at_rest_encryption_test.go
rules/aws/autoscaling/enforce_http_token_imds_test.go
rules/aws/autoscaling/no_public_ip_test.go
rules/aws/autoscaling/no_secrets_in_user_data_test.go
rules/aws/autoscaling/no_sensitive_info_test.go

feat: add unit tests for AWS AutoScaling rules

---

rules/aws/rds/enable_performance_insights_test.go
rules/aws/rds/encrypt_cluster_storage_data_test.go
rules/aws/rds/encrypt_instance_storage_data_test.go
rules/aws/rds/no_classic_resources_test.go
rules/aws/rds/no_public_db_access_test.go
rules/aws/rds/specify_backup_retention_test.go

feat: add unit tests for AWS RDS rules

---

rules/aws/workspaces/enable_disk_encryption_test.go

feat: add unit tests for AWS Workspaces rules

---

rules/aws/cloudfront/enable_logging_test.go
rules/aws/cloudfront/enable_waf_test.go
rules/aws/cloudfront/enforce_https_test.go
rules/aws/cloudfront/use_secure_tls_policy_test.go

feat: add unit tests for AWS CloudFront rules

---

rules/aws/cloudwatch/log_group_customer_key_test.go

feat: add unit tests for AWS CloudWatch rules

---

rules/aws/ebs/enable_volume_encryption_test.go
rules/aws/ebs/encryption_customer_key_test.go

feat: add unit tests for AWS EBS rules

---

rules/aws/codebuild/enable_encryption_test.go

feat: add unit tests for AWS Codebuild rules

---

rules/aws/elasticsearch/enable_domain_encryption_test.go
rules/aws/elasticsearch/enable_domain_logging_test.go
rules/aws/elasticsearch/enable_in_transit_encryption_test.go
rules/aws/elasticsearch/enforce_https_test.go
rules/aws/elasticsearch/use_secure_tls_policy_test.go

feat: add unit tests for AWS Elasticsearch rules

---

rules/aws/elasticache/add_description_for_security_group_test.go
rules/aws/elasticache/enable_at_rest_encryption_test.go
rules/aws/elasticache/enable_backup_retention_test.go
rules/aws/elasticache/enable_in_transit_encryption_test.go

feat: add unit tests for AWS ElastiCache rules

---

rules/aws/config/aggregate_all_regions_test.go

feat: add unit tests for AWS Config rules

---

rules/aws/neptune/enable_log_export_test.go
rules/aws/neptune/enable_storage_encryption_test.go
rules/aws/neptune/encryption_customer_key_test.go

feat: add unit tests for AWS Neptune rules

---

rules/aws/lambda/enable_tracing_test.go
rules/aws/lambda/restrict_source_arn_test.go

feat: add unit tests for AWS Lambda rules

---

rules/aws/mq/enable_audit_logging_test.go
rules/aws/mq/enable_general_logging_test.go
rules/aws/mq/no_public_access_test.go

feat: add unit tests for AWS MQ rules

---

rules/aws/apigateway/enable_access_logging_test.go
rules/aws/apigateway/enable_cache_encryption_test.go
rules/aws/apigateway/enable_tracing_test.go
rules/aws/apigateway/no_public_access_test.go
rules/aws/apigateway/use_secure_tls_policy_test.go

feat: add unit tests for AWS API Gateway rules

---

rules/aws/sns/enable_topic_encryption_test.go

feat: add unit tests for AWS SNS rules

---

rules/aws/msk/enable_in_transit_encryption_test.go
rules/aws/msk/enable_logging_test.go

feat: add unit tests for AWS MSK rules

---

rules/aws/redshift/add_description_to_security_group_test.go
rules/aws/redshift/encryption_customer_key_test.go
rules/aws/redshift/no_classic_resources_test.go
rules/aws/redshift/use_vpc_test.go

feat: add unit tests for AWS Redshift rules

---

rules/aws/athena/enable_at_rest_encryption_test.go
rules/aws/athena/no_encryption_override_test.go

feat: add unit tests for AWS Athena rules

---

rules/aws/sqs/enable_queue_encryption_test.go
rules/aws/sqs/no_wildcards_in_policy_documents_test.go

feat: add unit tests for AWS SQS rules

---

rules/aws/cloudtrail/enable_all_regions_test.go
rules/aws/cloudtrail/enable_at_rest_encryption_test.go
rules/aws/cloudtrail/enable_log_validation_test.go

feat: add unit tests for AWS CloudTrail rules

---

rules/aws/vpc/add_description_to_security_group_rule_test.go
rules/aws/vpc/add_description_to_security_group_test.go
rules/aws/vpc/no_default_vpc_test.go
rules/aws/vpc/no_excessive_port_access_test.go
rules/aws/vpc/no_public_egress_sgr_test.go
rules/aws/vpc/no_public_ingress_acl_test.go
rules/aws/vpc/no_public_ingress_sgr_test.go

feat: add unit tests for AWS VPC rules

---

rules/aws/dynamodb/enable_at_rest_encryption_test.go
rules/aws/dynamodb/enable_recovery_test.go
rules/aws/dynamodb/table_customer_key_test.go

feat: add unit tests for AWS DynamoDB rules

---

rules/aws/ecr/enable_image_scans_test.go
rules/aws/ecr/enforce_immutable_repository_test.go
rules/aws/ecr/no_public_access_test.go
rules/aws/ecr/repository_customer_key_test.go

feat: add unit tests for AWS ECR rules

---

rules/aws/ecs/enable_container_insight_test.go
rules/aws/ecs/enable_in_transit_encryption_test.go
rules/aws/ecs/no_plaintext_secrets_test.go

feat: add unit tests for AWS ECS rules

---

rules/aws/elb/alb_not_public_test.go
rules/aws/elb/drop_invalid_headers_test.go
rules/aws/elb/http_not_used_test.go
rules/aws/elb/use_secure_tls_policy_test.go

feat: add unit tests for AWS ELB rules

---

rules/aws/iam/enforce_mfa_test.go
rules/aws/iam/no_password_reuse_test.go
rules/aws/iam/no_policy_wildcards_test.go
rules/aws/iam/require_lowercase_in_passwords_test.go
rules/aws/iam/require_numbers_in_passwords_test.go
rules/aws/iam/require_symbols_in_passwords_test.go
rules/aws/iam/require_uppercase_in_passwords_test.go
rules/aws/iam/set_max_password_age_test.go
rules/aws/iam/set_minimum_password_length_test.go

feat: add unit tests for AWS IAM rules

---

rules/aws/s3/block_public_acls_test.go
rules/aws/s3/block_public_policy_test.go
rules/aws/s3/enable_bucket_encryption_test.go
rules/aws/s3/enable_bucket_logging_test.go
rules/aws/s3/enable_versioning_test.go
rules/aws/s3/ignore_public_acls_test.go
rules/aws/s3/no_public_access_with_acl_test.go
rules/aws/s3/no_public_buckets_test.go
rules/aws/s3/specify_public_access_block_test.go

feat: add unit tests for AWS S3 rules

---

rules/azure/compute/disable_password_authentication_test.go
rules/azure/compute/enable_disk_encryption_test.go
rules/azure/compute/no_secrets_in_custom_data_test.go

feat: add unit tests for Azure Compute rules

---

rules/azure/datafactory/no_public_access_test.go

feat: add unit tests for Azure Data Factory rules

---

rules/azure/datalake/enable_at_rest_encryption_test.go

feat: add unit tests for Azure Data Lake rules

---

rules/azure/synapse/virtual_network_enabled_test.go

feat: add unit tests for Azure Synapse rules

---

rules/azure/monitor/activity_log_retention_set_test.go
rules/azure/monitor/capture_all_activities_test.go
rules/azure/monitor/capture_all_regions_test.go

feat: add unit tests for Azure Monitor rules

---

rules/azure/database/all_threat_alerts_enabled_test.go
rules/azure/database/enable_audit_test.go
rules/azure/database/enable_ssl_enforcement_test.go
rules/azure/database/no_public_access_test.go
rules/azure/database/no_public_firewall_access_test.go
rules/azure/database/postgres_configuration_connection_throttling_test.go
rules/azure/database/postgres_configuration_log_checkpoints_test.go
rules/azure/database/postgres_configuration_log_connections_test.go
rules/azure/database/retention_period_set_test.go
rules/azure/database/secure_tls_policy_test.go
rules/azure/database/threat_alert_email_set_test.go
rules/azure/database/threat_alert_email_to_owner_test.go

feat: add unit tests for Azure Database rules

---

rules/azure/container/configured_network_policy_test.go
rules/azure/container/limit_authorized_ips_test.go
rules/azure/container/logging_test.go
rules/azure/container/use_rbac_permissions_test.go

feat: add unit tests for Azure Container rules

---

rules/azure/authorization/limit_role_actions_test.go

feat: add unit tests for Azure Authorization rules

---

rules/azure/appservice/account_identity_registered_test.go
rules/azure/appservice/authentication_enabled_test.go
rules/azure/appservice/enable_http2_test.go
rules/azure/appservice/enforce_https_test.go
rules/azure/appservice/require_client_cert_test.go
rules/azure/appservice/use_secure_tls_policy_test.go

feat: add unit tests for Azure AppService rules

---

rules/aws/sam/api_use_secure_tls_policy_test.go
rules/aws/sam/enable_api_access_logging_test.go
rules/aws/sam/enable_api_cache_encryption_test.go
rules/aws/sam/enable_api_tracing_test.go
rules/aws/sam/enable_function_tracing_test.go
rules/aws/sam/enable_http_api_access_logging_test.go
rules/aws/sam/enable_state_machine_logging_test.go
rules/aws/sam/enable_state_machine_tracing_test.go
rules/aws/sam/enable_table_encryption_test.go
rules/aws/sam/no_function_policy_wildcards_test.go
rules/aws/sam/no_state_machine_policy_wildcards_test.go

feat: add unit tests for AWS SAM rules

---

rules/google/dns/enable_dnssec_test.go
rules/google/dns/no_rsa_sha1_test.go

feat: add unit tests for Google DNS rules

---

rules/cloudstack/compute/no_sensitive_info_test.go

feat: add unit tests for Cloudstack Compute rules

---

rules/google/kms/rotate_kms_keys_test.go

feat: add unit tests for Google KMS rules

---

rules/github/actions/no_plain_text_action_secrets_test.go

feat: add unit tests for Github Actions rules

---

rules/github/repositories/private_test.go

feat: add unit tests for Github repositories rules

---

rules/google/storage/enable_ubla_test.go
rules/google/storage/no_public_access_test.go

feat: add unit tests for Google Storage rules

---

rules/kubernetes/network/no_public_egress_test.go
rules/kubernetes/network/no_public_ingress_test.go

feat: add unit tests for Kubernetes Network rules

---

rules/openstack/compute/no_plaintext_password_test.go
rules/openstack/compute/no_public_access_test.go

feat: add unit tests for OpenStack Compute rules

---

rules/oracle/compute/no_public_ip_test.go

feat: add unit tests for Oracle Compute rules

---

rules/digitalocean/spaces/acl_no_public_read_test.go
rules/digitalocean/spaces/disable_force_destroy_test.go
rules/digitalocean/spaces/versioning_enabled_test.go

feat: add unit tests for DigitalOcean Spaces rules

---

rules/digitalocean/compute/auto_upgrade_no_maintenance_policy_test.go
rules/digitalocean/compute/enforce_https_test.go
rules/digitalocean/compute/kubernetes_surge_upgrades_test.go
rules/digitalocean/compute/no_public_egress_test.go
rules/digitalocean/compute/no_public_ingress_test.go
rules/digitalocean/compute/use_ssh_keys_test.go

feat: add unit tests for DigitalOcean Compute rules

---

rules/google/compute/disk_encryption_customer_key_test.go
rules/google/compute/disk_encryption_no_plaintext_key_test.go
rules/google/compute/enable_shielded_vm_im_test.go
rules/google/compute/enable_shielded_vm_vtpm_test.go
rules/google/compute/enable_vpc_flow_logs_test.go
rules/google/compute/no_default_service_account_test.go
rules/google/compute/no_ip_forwarding_test.go
rules/google/compute/no_oslogin_override_test.go
rules/google/compute/no_project_wide_ssh_keys_test.go
rules/google/compute/no_public_egress_test.go
rules/google/compute/no_public_ingress_test.go
rules/google/compute/no_public_ip_test.go
rules/google/compute/no_serial_port_test.go
rules/google/compute/project_level_oslogin_test.go
rules/google/compute/use_secure_tls_policy_test.go
rules/google/compute/vm_disk_encryption_customer_key_test.go

feat: add unit tests for Google Compute rules

---

rules/google/gke/enable_auto_repair_test.go
rules/google/gke/enable_auto_upgrade_test.go
rules/google/gke/enable_ip_aliasing_test.go
rules/google/gke/enable_master_networks_test.go
rules/google/gke/enable_network_policy_test.go
rules/google/gke/enable_private_cluster_test.go
rules/google/gke/enable_stackdriver_logging_test.go
rules/google/gke/enable_stackdriver_monitoring_test.go
rules/google/gke/enforce_pod_security_policy_test.go
rules/google/gke/metadata_endpoints_disabled_test.go
rules/google/gke/no_legacy_authentication_test.go
rules/google/gke/no_public_control_plane_test.go
rules/google/gke/node_metadata_security_test.go
rules/google/gke/node_pool_uses_cos_test.go
rules/google/gke/node_shielding_enabled_test.go
rules/google/gke/use_cluster_labels_test.go
rules/google/gke/use_rbac_permissions_test.go
rules/google/gke/use_service_account_test.go

feat: add unit tests for Google GKE rules

---

rules/google/iam/no_default_network_test.go
rules/google/iam/no_folder_level_default_service_account_assignment_test.go
rules/google/iam/no_folder_level_service_account_impersonation_test.go
rules/google/iam/no_org_level_default_service_account_assignment_test.go
rules/google/iam/no_org_level_service_account_impersonation_test.go
rules/google/iam/no_privileged_service_accounts_test.go
rules/google/iam/no_project_level_default_service_account_assignment_test.go
rules/google/iam/no_project_level_service_account_impersonation_test.go
rules/google/iam/no_user_granted_permissions_test.go

feat: add unit tests for Google IAM rules

---

rules/google/sql/enable_backup_test.go
rules/google/sql/enable_pg_temp_file_logging_test.go
rules/google/sql/encrypt_in_transit_data_test.go
rules/google/sql/mysql_no_local_infile_test.go
rules/google/sql/no_contained_db_auth_test.go
rules/google/sql/no_cross_db_ownership_chaining_test.go
rules/google/sql/no_public_access_test.go
rules/google/sql/pg_log_checkpoints_test.go
rules/google/sql/pg_log_connections_test.go
rules/google/sql/pg_log_disconnections_test.go
rules/google/sql/pg_log_errors_test.go
rules/google/sql/pg_log_lock_waits_test.go
rules/google/sql/pg_no_min_statement_logging_test.go

feat: add unit tests for Google SQL rules

---

adapters/terraform/azure/database/adapt.go
adapters/terraform/azure/database/adapt_test.go

Fix: process all azurerm postgres config blocks

---

adapters/terraform/aws/s3/adapt.go
adapters/terraform/aws/s3/bucket.go
adapters/terraform/aws/s3/bucket_test.go
rules/aws/s3/enable_bucket_encryption.tf.go
rules/aws/s3/enable_bucket_logging.tf.go
rules/aws/s3/enable_versioning.tf.go
rules/aws/s3/no_public_access_with_acl.tf.go

feat: add AWS provider v4 support

---

adapters/terraform/azure/appservice/adapt_test.go

test: azure appservice tf adapters

---

adapters/terraform/azure/authorization/adapt.go
adapters/terraform/azure/authorization/adapt_test.go

test: azure authorization tf adapter

---

adapters/terraform/aws/cloudwatch/adapt.go
adapters/terraform/aws/cloudwatch/adapt_test.go

test: aws cloudwatch tf adapter

---

adapters/terraform/aws/autoscaling/adapt_test.go

test: aws autoscaling tf adapter

---

adapters/terraform/google/bigquery/adapt_test.go

test: google bigquery tf adapter

---

adapters/terraform/openstack/adapt_test.go

test: openstack tf adapter

---

adapters/terraform/github/repositories/adapt.go
adapters/terraform/github/repositories/adapt_test.go
avd_docs/github/repositories/AVD-GIT-0003/Terraform.md
avd_docs/github/repositories/AVD-GIT-0003/docs.md
providers/github/repositories.go
rules/github/repositories/enable_vulnerability_alerts.go
rules/github/repositories/enable_vulnerability_alerts.tf.go
rules/github/repositories/enable_vulnerability_alerts_test.go

Fixes https://github.com/aquasecurity/tfsec/issues/1569

feat: Check GitHub repositories to ensure vulnerability alerts are enabled

---

adapters/terraform/azure/compute/adapt.go
adapters/terraform/azure/compute/adapt_test.go

test: add tests for azure compute tf adapters

---

adapters/terraform/aws/sqs/adapt.go
adapters/terraform/aws/sqs/adapt_test.go

test: add tests for aws sqs tf adapters

---

adapters/terraform/aws/sns/adapt_test.go

test: add tests for aws sns tf adapters

---

adapters/terraform/azure/container/adapt.go
adapters/terraform/azure/container/adapt_test.go

test: add azure container tests for tf adapters

---

adapters/terraform/azure/securitycenter/adapt.go
adapters/terraform/azure/securitycenter/adapt_test.go

test: add azure security center tests for tf adapters

---

adapters/terraform/azure/monitor/adapt.go
adapters/terraform/azure/monitor/adapt_test.go

test: add tests for azure monitor tf adapters

---

adapters/terraform/azure/keyvault/adapt_test.go

test: add tests for azure keyvault tf adapters

---

adapters/terraform/cloudstack/compute/adapt.go
adapters/terraform/cloudstack/compute/adapt_test.go

test: add cloudstack compute tests for tf adapters

---

adapters/terraform/azure/synapse/adapt_test.go

test: add tests for azure synapse tf adapters

---

adapters/terraform/azure/datalake/adapt.go
adapters/terraform/azure/datalake/adapt_test.go

test: add tests for azure datalake tf adapters

---

adapters/terraform/azure/datafactory/adapt_test.go

test: add tests for azure datafactory tf adapters

---

avd_docs/aws/rds/AVD-AWS-0133/CloudFormation.md
avd_docs/aws/rds/AVD-AWS-0133/Terraform.md
avd_docs/aws/rds/AVD-AWS-0133/docs.md
rules/aws/rds/enable_performance_insights.go
rules/aws/rds/enable_performance_insights.tf.go
rules/aws/rds/enable_performance_insights_encryption.cf.go
rules/aws/rds/enable_performance_insights_encryption.go
rules/aws/rds/enable_performance_insights_encryption.tf.go
rules/aws/rds/enable_performance_insights_encryption_test.go

feat: Split checks for performance insight enable and encrypt out

---

adapters/terraform/aws/ecr/adapt.go
adapters/terraform/aws/ecr/adapt_test.go

test: add tests for aws ecr tf adapters

---

adapters/terraform/aws/ec2/adapt_test.go

test: add tests for aws ec2 tf adapters

---

adapters/terraform/aws/ebs/adapt.go
adapters/terraform/aws/ebs/adapt_test.go

test: add tests for aws ebs tf adapters

---

adapters/terraform/aws/dynamodb/adapt.go
adapters/terraform/aws/dynamodb/adapt_test.go

test: add tests for aws dynamodb tf adapters

---

adapters/terraform/aws/documentdb/adapt_test.go

test: add tests for aws docdb tf adapters

---

adapters/terraform/aws/config/adapt_test.go

test: add tests for aws config tf adapters

---

adapters/terraform/aws/codebuild/adapt_test.go

test: add tests for aws codebuild tf adapters

---

adapters/terraform/aws/cloudtrail/adapt_test.go

test: add tests for aws cloudtrail tf adapters

---

adapters/terraform/aws/cloudfront/adapt_test.go

test: add tests for aws cloudfront tf adapters

---

adapters/terraform/google/dns/adapt.go
adapters/terraform/google/dns/adapt_test.go

test: add tests for google dns tf adapters

---

adapters/terraform/google/kms/adapt.go
adapters/terraform/google/kms/adapt_test.go

test: add tests for google kms adapters

---

parsers/terraform/parser/parser.go
scanners/terraform/scanner.go

See https://github.com/aquasecurity/tfsec/issues/1595

fix: resolve symlinks with different names

---

scanners/terraform/executor/executor.go

See https://github.com/aquasecurity/tfsec/issues/1597

fix: Exclude rules

---

scanners/terraform/executor/executor.go

(created on mobile, brace for formatting issues)

fix: Use custom filter options on results

---

rules/aws/cloudfront/use_secure_tls_policy.go
rules/aws/cloudfront/use_secure_tls_policy.tf.go

Resolves aquasecurity/tfsec#1515

docs: update documentation for cloudfront rule

---

adapters/terraform/aws/elb/adapt.go
providers/aws/elb/elb.go
rules/aws/elb/drop_invalid_headers_test.go

Resolves #448 
Signed-off-by: Owen Rumney <owen@owenrumney.co.uk>

fix: fix 448 classic elb doesn't have same attributes as alb

---

adapters/terraform/aws/ecs/adapt.go
adapters/terraform/aws/ecs/adapt_test.go

test: add tests for aws ecs tf adapters

---

adapters/terraform/aws/elb/adapt_test.go

test: add tests for aws elb adapters

---

adapters/terraform/aws/kinesis/adapt_test.go

test: add tests for aws kinesis tf adapters

---

adapters/terraform/aws/workspaces/adapt.go
adapters/terraform/aws/workspaces/adapt_test.go

test: add tests for aws workspaces tf adapters

---

adapters/terraform/aws/neptune/adapt.go
adapters/terraform/aws/neptune/adapt_test.go

test: add tests for aws neptune tf adapters

---

adapters/terraform/aws/msk/adapt.go
adapters/terraform/aws/msk/adapt_test.go

test: add tests for aws msk tf adapters

---

adapters/terraform/aws/mq/adapt_test.go

test: add  tests for aws mq tf adapters

---

adapters/terraform/aws/kms/adapt_test.go

test: add tests for aws kms tf adapters

---

adapters/terraform/aws/elasticsearch/adapt_test.go

test: add tests for aws elasticsearch tf adapters

---

adapters/terraform/aws/eks/adapt_test.go

test: add tests for aws eks tf adapters

---

adapters/terraform/digitalocean/spaces/adapt_test.go

test: add tests for digitalocean spaces tf adapters

---

adapters/terraform/aws/ssm/adapt.go
adapters/terraform/aws/ssm/adapt_test.go

test: add tests for aws ssm tf adapters

---

adapters/terraform/aws/efs/adapt_test.go

test: add tests for aws efs tf adapters

---

parsers/terraform/parser/resolvers/remote.go

chore: make the created folder for downloaded content deletable

---

pkg/scanners/terraform/parser/resolvers/cache.go
pkg/scanners/terraform/parser/resolvers/writable.go
pkg/scanners/terraform/parser/resolvers/writable_windows.go

fix: Fix Windows support

---

pkg/scanners/terraform/options.go

feat(terraform): Customisable filter functions for scan results

---

.github/workflows/build.yml

build(actions): Add cache action to speed up builds

---

pkg/scanners/cloudformation/parser/property.go

fix(cloudformation): Fix margin removal for empty lines

---

internal/adapters/terraform/azure/keyvault/adapt.go
internal/rules/azure/keyvault/ensure_secret_expiry.tf.go
internal/types/time_value.go

fix(azurerm): Fix false positive on key vault secret expiration

---

internal/adapters/terraform/azure/network/adapt.go
internal/rules/azure/network/disable_rdp_from_internet.go
internal/rules/azure/network/disable_rdp_from_internet_test.go
internal/rules/azure/network/ssh_blocked_from_internet.go
internal/rules/azure/network/ssh_blocked_from_internet_test.go
pkg/providers/azure/network/network.go

fix(check): Fix false positive for azure network security rules

---

internal/adapters/terraform/google/gke/adapt.go
internal/rules/google/gke/metadata_endpoints_disabled.tf.go

fix(google): Fix GKE legacy endpoint use detection 

---

pkg/scanners/terraform/executor/executor.go
pkg/scanners/terraform/executor/option.go
pkg/scanners/terraform/executor/pool.go
pkg/scanners/terraform/options.go
pkg/scanners/terraform/scanner_test.go

feat(terraform): Add option to only apply rego policies

---

internal/rules/defsec/lib/defsec.rego
internal/types/bool_value.go
internal/types/bytes_value.go
internal/types/fskey.go
internal/types/fskey_test.go
internal/types/int_value.go
internal/types/map_value.go
internal/types/metadata.go
internal/types/range.go
internal/types/string_value.go
internal/types/time_value.go
pkg/rego/result.go
pkg/scanners/terraform/parser/evaluator.go
pkg/scanners/terraform/parser/parser.go
pkg/scanners/terraform/scanner.go
pkg/scanners/terraform/scanner_test.go
pkg/state/state_test.go

feat(terraform): Make source-code available for results obtained though scanning tf with rego

---

pkg/scanners/cloudformation/parser/parser_test.go
pkg/scanners/kubernetes/parser/parser.go
pkg/scanners/kubernetes/scanner.go
pkg/scanners/kubernetes/scanner_test.go
pkg/scanners/yaml/parser/parser.go
pkg/scanners/yaml/parser/parser_test.go
pkg/scanners/yaml/scanner.go

feat(parser): Add capability to parse separated yaml files

---

internal/rules/kubernetes/policies/general/runs_with_GID_le_10000.rego
internal/rules/kubernetes/policies/general/runs_with_UID_le_10000.rego
internal/rules/kubernetes/policies/general/uses_image_tag_latest.rego

Changed some severities for some checks

chore: downgrade some severities

---

pkg/scanners/terraformplan/parser/parser.go
pkg/scanners/terraformplan/parser/plan_file.go
pkg/scanners/terraformplan/scanner.go
pkg/scanners/terraformplan/test/scanner_test.go
pkg/terraform/resource_block.go

fix(plan): update scanning to cover more areas

---

internal/adapters/terraform/aws/redshift/adapt.go
internal/adapters/terraform/aws/redshift/adapt_test.go

test: add tests for aws redshift tf adapters

---

pkg/terraform/block.go
pkg/terraform/reference.go

fix: foreach key resolution

---

pkg/scanners/terraform/scanner_test.go

See https://aquasecurity.slack.com/archives/C02N70HUYNM/p1651004262752669

test: Add test for rego privileged container detection

---

pkg/scanners/terraform/scanner.go

fix(terraform): push debug writer to parser

---

internal/rules/defsec/lib/defsec.rego
internal/types/bool_value.go
internal/types/bytes_value.go
internal/types/int_value.go
internal/types/map_value.go
internal/types/metadata.go
internal/types/string_value.go
internal/types/time_value.go
pkg/rego/result.go
pkg/scanners/terraform/executor/pool.go
pkg/state/state_test.go
pkg/terraform/module.go

- Added proper (mainly Terraform) resource references
- Added base path of Terraform module to rego scan input

feat: Improve rego metadata in results

---

.github/workflows/release.yaml

fix(rego): Fix defsec package manifest listing

---

.github/workflows/build.yml
.github/workflows/test.yaml
pkg/extrafs/extrafs.go
pkg/scanners/terraform/parser/parser.go
pkg/scanners/terraform/scanner.go

fix: symlink resolution fix

---

go.mod
go.sum

chore(deps): bump squealer to get freebsd support

---

pkg/formatters/json.go
pkg/scanners/helm/parser/parser_tar.go

fix(formatting): json output couldn't return passed or ignored

---

internal/adapters/terraform/digitalocean/compute/adapt.go
internal/adapters/terraform/digitalocean/compute/adapt_test.go

test: add tests for digital-ocean compute tf adapters

---

internal/adapters/terraform/aws/vpc/adapt.go
internal/adapters/terraform/aws/vpc/adapt_test.go

test: add tests for aws vpc tf adapters

---

pkg/scan/code.go

- fix: remove Highlighted from json
- fix: Don't include Highlighted in Json

fix: remove Highlighted from code explicitly

---

pkg/scan/code.go

Reverts aquasecurity/defsec#600

Revert "fix: remove Highlighted from code explicitly"

---

pkg/scan/code.go

- fix: remove Highlighted from json
- fix: Don't include Highlighted in Json
- fix: add omit empty for Highlighted

fix: make highlight omit empty

---

pkg/scan/code.go
pkg/scan/code_test.go

See https://github.com/aquasecurity/trivy/issues/2141

feat: Truncate source code with an optional limit

---

internal/rules/kubernetes/policies/advanced/selector_usage_in_network_policies.rego
internal/rules/kubernetes/policies/advanced/selector_usage_in_network_policies_test.rego
pkg/scanners/helm/test/scanner_test.go

Closes  https://github.com/aquasecurity/defsec/issues/606

fix: False positives KSV038. Fix + test

---

internal/adapters/terraform/google/compute/adapt_test.go
internal/adapters/terraform/google/compute/disks.go
internal/adapters/terraform/google/compute/disks_test.go
internal/adapters/terraform/google/compute/instances.go
internal/adapters/terraform/google/compute/instances_test.go
internal/adapters/terraform/google/compute/metadata_test.go
internal/adapters/terraform/google/compute/networks.go
internal/adapters/terraform/google/compute/networks_test.go
internal/adapters/terraform/google/compute/ssl_test.go

test: add tests for google compute tf adapters

---

internal/adapters/terraform/google/gke/adapt.go
internal/adapters/terraform/google/gke/adapt_test.go

resolves #616 
additional changes:
- refactor adapters for more precise block metadata

test: add tests for google gke tf adapters

---

internal/adapters/terraform/google/sql/adapt.go
internal/adapters/terraform/google/sql/adapt_test.go

test: add tests for google sql tf adapters

---

avd_docs/google/compute/AVD-GCP-0027/Terraform.md
internal/adapters/terraform/google/compute/networks.go
internal/rules/google/compute/no_public_ingress.go
internal/rules/google/compute/no_public_ingress.tf.go
pkg/providers/google/compute/firewall.go
pkg/terraform/attribute.go

fix: support source/target tags for GCP firewall

---

internal/rules/azure/network/no_public_ingress.go
internal/rules/azure/network/no_public_ingress.tf.go
pkg/scanners/helm/parser/parser_tar.go

fix: Single public IPs should ba acceptable as prefixes

---

internal/adapters/terraform/google/storage/adapt_test.go

test: add tests for google storage tf adapters

---

internal/adapters/terraform/azure/storage/adapt.go
internal/adapters/terraform/azure/storage/adapt_test.go

test: add tests for azure storage tf adapters

---

internal/adapters/terraform/azure/network/adapt_test.go

test: add tests for azure network tf adapters

---

internal/rules/aws/ebs/encryption_customer_key.cf.go
internal/types/metadata.go
pkg/scanners/cloudformation/parser/intrinsics.go
pkg/scanners/cloudformation/parser/property.go
pkg/scanners/cloudformation/parser/property_helpers.go
pkg/scanners/cloudformation/parser/resource.go

feat(cloudformation): Add support for unresolvable values e.g. via ImportValue

---

go.mod
go.sum

Resolves https://github.com/aquasecurity/defsec/security/dependabot/3

chore(deps): Upgrade yaml.v3 to v3.0.0

---

internal/rules/aws/s3/enable_bucket_logging.cf.go
pkg/scanners/cloudformation/parser/fn_ref_test.go
pkg/scanners/cloudformation/parser/intrinsics.go
pkg/scanners/cloudformation/parser/property.go

fix(cloudformation): Fix unresolved values being equated with empty ones

---

internal/rules/aws/s3/enable_bucket_encryption.tf.go
pkg/terraform/block.go
test/module_test.go

fix(terraform): Fix resolution of provider-added values e.g. arn/id

---

internal/adapters/cloudformation/aws/sqs/queue.go
internal/adapters/terraform/aws/sqs/adapt.go
internal/adapters/terraform/aws/sqs/adapt_test.go
internal/rules/aws/sqs/enable_queue_encryption.cf.go
internal/rules/aws/sqs/enable_queue_encryption.go
internal/rules/aws/sqs/enable_queue_encryption.tf.go
internal/rules/aws/sqs/enable_queue_encryption_test.go
pkg/providers/aws/sqs/sqs.go

feat: support managed encryption for sqs

---

pkg/detection/detect.go
pkg/detection/detect_test.go

feat(Dockerfile): Add support for 'Containerfile' detection as required by trivy/fanal

---

internal/adapters/terraform/azure/container/adapt_test.go
pkg/terraform/attribute.go

fix: Fix unresolved string slice behaviour

---

internal/rules/kubernetes/README.md

Changes:
* Updated command lines in order to fail the denied input
* Updated description to match the updated command lines

Corrections to rules/kubernetes README

---

pkg/terraform/attribute.go

helps with aquasecurity/tfsec#1689

feat: support dynamic values where possible in listContains

---

internal/rules/aws/s3/encryption_customer_key.go
internal/rules/aws/s3/encryption_customer_key.tf.go

feat: don't enforce CMK on log buckets

---

avd_docs/azure/container/AVD-AZU-0042/Terraform.md
internal/adapters/terraform/azure/container/adapt.go
internal/rules/azure/container/use_rbac_permissions.tf.go

fix: support more recent RBAC config blocks in AKS

---

avd_docs/kubernetes/general/AVD-KSV-0103/docs.md
avd_docs/kubernetes/general/AVD-KSV-0104/docs.md
cmd/avd_generator/main.go
cmd/id/main.go
internal/rules/kubernetes/policies/pss/baseline/10_windows_host_process.rego
internal/rules/kubernetes/policies/pss/baseline/10_windows_host_process_test.rego
internal/rules/kubernetes/policies/pss/baseline/11_seccomp_profile_unconfined.rego
internal/rules/kubernetes/policies/pss/baseline/11_seccomp_profile_unconfined_test.rego

fix(kubernetes): Add missing PSS baseline policies

---

internal/adapters/terraform/azure/storage/adapt.go

fix: assume the worst case when the allow by default var not evaluable

---

pkg/scanners/kubernetes/parser/manifest_node.go

fix: Add support for missing types in Kubernetes yaml

---

pkg/debug/debug.go

chore: Added more debug vars

---

pkg/detection/detect.go
pkg/detection/detect_test.go
pkg/scanners/cloudformation/parser/parser.go

See https://github.com/aquasecurity/trivy/issues/2382

fix: Improve CloudFormation detection and ignore individual file parse errors

---

avd_docs/rbac/general/AVD-KSV-0044/docs.md
avd_docs/rbac/general/AVD-KSV-0045/docs.md
avd_docs/rbac/general/AVD-KSV-0046/docs.md
avd_docs/rbac/general/AVD-KSV-0048/docs.md
avd_docs/rbac/general/AVD-KSV-0050/docs.md
avd_docs/rbac/general/AVD-KSV-0051/docs.md
avd_docs/rbac/general/AVD-KSV-0052/docs.md
avd_docs/rbac/general/AVD-KSV-0054/docs.md
internal/rules/docker/lib/docker.rego
internal/rules/docker/policies/copy_from_references_current_from_alias.rego
internal/rules/docker/policies/copy_from_references_current_from_alias_test.rego

See https://github.com/aquasecurity/trivy/issues/2394

fix: Fix docker rego bug where same FROM ref causes crash

---

internal/rules/google/gke/node_pool_uses_cos.go

See https://github.com/aquasecurity/trivy/issues/2398

fix: False positive on use of containerd cos image

---

internal/adapters/terraform/aws/iam/passwords.go
internal/adapters/terraform/aws/s3/public_access_block.go
pkg/terraform/attribute.go

fix: Handle numbers that are in strings

---

internal/adapters/terraform/azure/network/adapt.go
pkg/terraform/attribute.go

Goes towards fixing https://github.com/aquasecurity/tfsec/issues/1823

fix: Switch to using asIntegerOrDefault with AsNumber

---

internal/adapters/terraform/aws/iam/adapt_test.go
internal/adapters/terraform/aws/iam/groups_test.go
internal/adapters/terraform/aws/iam/passwords_test.go
internal/adapters/terraform/aws/iam/policies_test.go
internal/adapters/terraform/aws/iam/users_test.go

test: add tests for aws iam tf adapters

---

internal/adapters/terraform/google/gke/adapt.go
internal/adapters/terraform/google/gke/adapt_test.go
internal/rules/google/gke/metadata_endpoints_disabled.tf.go

fix(Terraform): Fix GKE node pool metadata parsing

---

internal/adapters/terraform/aws/s3/adapt_test.go
internal/adapters/terraform/aws/s3/bucket.go

test: add tests for aws s3 tf adapters

---

internal/rules/aws/cloudtrail/enable_all_regions.go
internal/rules/aws/iam/enforce_mfa.go
internal/rules/aws/iam/no_password_reuse.go
internal/rules/aws/iam/require_lowercase_in_passwords.go
internal/rules/aws/iam/require_numbers_in_passwords.go
internal/rules/aws/iam/require_symbols_in_passwords.go
internal/rules/aws/iam/require_uppercase_in_passwords.go
internal/rules/aws/iam/set_minimum_password_length.go
internal/rules/aws/vpc/no_public_ingress_sgr.go
internal/rules/register.go
internal/rules/register_test.go
pkg/framework/frameworks.go
pkg/rego/metadata.go
pkg/scan/rule.go
pkg/scanners/cloudformation/scanner_test.go
pkg/scanners/dockerfile/scanner_test.go
pkg/scanners/json/scanner_test.go
pkg/scanners/kubernetes/scanner_test.go
pkg/scanners/rbac/scanner_test.go
pkg/scanners/toml/scanner_test.go
pkg/scanners/yaml/scanner_test.go

feat: Add framework references specification option for all rules

---

Makefile
go.mod
go.sum
internal/adapters/cloud/aws/cloudtrail/adapt.go
internal/adapters/cloud/aws/cloudwatch/adapt.go
internal/rules/aws/cloudwatch/require_unauthorised_api_call_alarm.go
internal/rules/aws/cloudwatch/require_unauthorised_api_call_alarm_test.go
internal/types/string_value.go
pkg/providers/aws/cloudtrail/cloudtrail.go
pkg/providers/aws/cloudwatch/cloudwatch.go

Resolves #748
- feat: cloudtrail unauthorised metric
- feat: Check that there is an alarm for unauthorized api calls

feat: Check for unauthorized api call alarm

---

internal/rules/aws/cloudwatch/require_non_mfa_login_alarm.go
internal/rules/aws/cloudwatch/require_non_mfa_login_alarm_test.go

Update metric avd id
Resolves #749

feat: check for non-MFA login alarm

---

internal/rules/aws/cloudwatch/require_non_mfa_login_alarm.go
internal/rules/aws/cloudwatch/require_unauthorised_api_call_alarm.go

fix: Correct Framework IDs

---

avd_docs/aws/cloudtrail/AVD-AWS-0163/docs.md
internal/adapters/cloud/aws/cloudtrail/adapt.go
internal/adapters/cloudformation/aws/cloudtrail/trails.go
internal/adapters/terraform/aws/cloudtrail/adapt.go
internal/adapters/terraform/aws/cloudtrail/adapt_test.go
internal/rules/aws/cloudtrail/require_bucket_access_logging.cf.go
internal/rules/aws/cloudtrail/require_bucket_access_logging.go
internal/rules/aws/cloudtrail/require_bucket_access_logging.tf.go
internal/rules/aws/cloudtrail/require_bucket_access_logging_test.go
pkg/providers/aws/cloudtrail/cloudtrail.go
pkg/scanners/helm/scanner.go

feat: Add CloudTrail CIS AWS 2.6 Rule

---

avd_docs/aws/cloudwatch/AVD-AWS-0147/docs.md
avd_docs/aws/cloudwatch/AVD-AWS-0148/docs.md
avd_docs/aws/cloudwatch/AVD-AWS-0149/docs.md
avd_docs/aws/iam/AVD-AWS-0142/docs.md
avd_docs/aws/iam/AVD-AWS-0144/docs.md
avd_docs/aws/iam/AVD-AWS-0145/docs.md
avd_docs/aws/iam/AVD-AWS-0146/docs.md
cmd/avd_generator/main.go
internal/rules/aws/cloudwatch/require_root_user_usage_alarm.go
internal/rules/aws/cloudwatch/require_root_user_usage_alarm_test.go
internal/rules/register.go
pkg/framework/frameworks.go
pkg/scanners/helm/scanner.go

- feat: Add check for root user usage alarm
- feat: add check for root usage

feat: root user usage alarm

---

avd_docs/aws/cloudwatch/AVD-AWS-0148/docs.md
avd_docs/aws/cloudwatch/AVD-AWS-0150/docs.md
internal/rules/aws/cloudwatch/require_iam_policy_change_alarm.go
internal/rules/aws/cloudwatch/require_iam_policy_change_alarm_test.go

feat: add check for IAM policy change alarm

---

avd_docs/aws/cloudtrail/AVD-AWS-0161/docs.md
avd_docs/aws/cloudtrail/AVD-AWS-0162/docs.md
internal/adapters/cloudformation/aws/cloudtrail/trails.go
internal/adapters/terraform/aws/cloudtrail/adapt.go
internal/adapters/terraform/aws/cloudtrail/adapt_test.go
internal/rules/aws/cloudtrail/ensure_cloudwatch_integration.cf.go
internal/rules/aws/cloudtrail/ensure_cloudwatch_integration.go
internal/rules/aws/cloudtrail/ensure_cloudwatch_integration.tf.go
internal/rules/aws/cloudtrail/ensure_cloudwatch_integration_test.go
internal/rules/aws/cloudtrail/no_public_log_access.cf.go
internal/rules/aws/cloudtrail/no_public_log_access.go
internal/rules/aws/cloudtrail/no_public_log_access.tf.go
internal/rules/aws/cloudtrail/no_public_log_access_test.go
internal/rules/aws/cloudtrail/require_bucket_access_logging.go

feat: Add remaining aws cis 1.2 cloudtrail checks

---

pkg/scanners/helm/options.go
pkg/scanners/helm/parser/option.go
pkg/scanners/helm/parser/parser.go
pkg/scanners/helm/parser/vals.go
pkg/scanners/helm/scanner.go
pkg/scanners/helm/test/option_test.go
pkg/scanners/helm/test/testdata/expected/options/testchart/templates/deployment.yaml
pkg/scanners/helm/test/testdata/expected/options/testchart/templates/service.yaml
pkg/scanners/helm/test/testdata/expected/options/testchart/templates/serviceaccount.yaml
pkg/scanners/helm/test/values/values.yaml

- feat: add support for passing Helm values files
- chore: switch to all variadic values
- fix: implement interface for Configurable scanner

feat: support helm value overrides

---

cmd/defsec/main.go
internal/adapters/cloudformation/aws/iam/policy.go

fix: Fix issue with scanning a CloudFormation IAM policy with omitted policy document

---

internal/adapters/cloud/aws/s3/s3.go
internal/adapters/cloud/aws/workspaces/adapt.go

- feat: EVERYTHING individually concurrent
- fix: linting issues
- fix: make s3 adapt bucket concurrent the same

fix: make s3 adapt function consistent

---

internal/adapters/cloud/aws/s3/s3.go

debug logging is pretty vocal on the errors, clean up by checking the
code isn't the standard response

fix: clean up the debug logging for s3

---

internal/adapters/cloud/aws/s3/s3.go

fix: switch to casting aws errors

---

internal/adapters/cloud/aws/adapt.go
internal/adapters/cloud/aws/s3/s3.go
pkg/errors/adapter.go
pkg/errs/adapter.go
pkg/scanners/cloud/aws/scanner.go

fix: show errors on adapter failure

---

internal/adapters/terraform/aws/iam/groups.go
internal/adapters/terraform/aws/iam/roles.go
internal/adapters/terraform/aws/iam/users.go
internal/adapters/terraform/google/iam/org_iam.go
test/ignore_test.go

fix: Allow ignores of implied IAM resources

---

internal/adapters/cloud/aws/elb/adapt.go

See https://twitter.com/kthrtty/status/1559491282438787073

fix: Handle nil pointer for ssl policy

---

internal/adapters/terraform/google/compute/adapt_test.go
internal/adapters/terraform/google/compute/instances.go
internal/adapters/terraform/google/compute/instances_test.go
internal/rules/google/compute/no_default_service_account.go
internal/rules/google/compute/no_default_service_account_test.go
pkg/providers/google/compute/instance.go

fix: Fix detection of default service account usage on GCP compute instance

---

pkg/scanners/terraform/parser/load_module.go

fix: Fix module loading from modules.json

---

internal/adapters/terraform/aws/ecr/adapt.go
internal/adapters/terraform/aws/ecr/adapt_test.go
internal/adapters/terraform/aws/iam/convert.go
internal/adapters/terraform/aws/sqs/adapt.go
pkg/terraform/block.go
pkg/terraform/module.go
pkg/terraform/modules.go

fix: Handle chained references for IAM policies when special 'json' property is used

---

internal/adapters/terraform/aws/s3/public_access_block.go
pkg/terraform/block.go
pkg/terraform/presets.go

Resolves https://github.com/aquasecurity/defsec/issues/880

fix(terraform): Fix bucket public access block referencing by implied id

---

pkg/scanners/terraform/parser/resolvers/remote.go

See https://github.com/aquasecurity/tfsec/issues/1859

fix(terraform): Fix remote module loading with ref

---

internal/adapters/terraform/aws/s3/bucket.go
pkg/terraform/presets.go

https://github.com/aquasecurity/tfsec/issues/1822

fix(terraform): Fix linking of s3 resources

---

internal/adapters/terraform/aws/s3/public_access_block.go

See https://github.com/aquasecurity/tfsec/issues/1863

fix: Public access block ref linking

---

pkg/rego/metadata.go
pkg/rego/scanner.go
pkg/rego/scanner_test.go

feat: support for dynamic metadata fields

---

avd_docs/aws/cloudwatch/AVD-AWS-0174/docs.md
avd_docs/aws/ec2/AVD-AWS-0173/docs.md
internal/adapters/cloud/aws/ec2/ec2.go
internal/adapters/cloud/aws/ec2/vpc.go
internal/adapters/cloudformation/aws/ec2/ec2.go
internal/adapters/cloudformation/aws/ec2/security_group.go
internal/adapters/terraform/aws/ec2/adapt.go
internal/adapters/terraform/aws/ec2/vpc.go
internal/adapters/terraform/aws/ec2/vpc_test.go
internal/rules/aws/cloudwatch/require_org_changes_alarm.go
internal/rules/aws/cloudwatch/require_org_changes_alarm_test.go
internal/rules/aws/ec2/enable_at_rest_encryption_test.go
internal/rules/aws/ec2/no_default_vpc.go
internal/rules/aws/ec2/no_default_vpc_test.go
internal/rules/aws/ec2/restrict_all_in_default_sg.go
internal/rules/aws/ec2/restrict_all_in_default_sg_test.go
pkg/providers/aws/ec2/ec2.go
pkg/providers/aws/ec2/vpc.go

feat: add remaining cis aws 1.4 rules

---

avd_docs/google/storage/AVD-GCP-0066/docs.md
internal/adapters/terraform/google/storage/adapt.go
internal/adapters/terraform/google/storage/adapt_test.go
internal/rules/google/storage/bucket_encryption_customer_key.go
internal/rules/google/storage/bucket_encryption_customer_key.tf.go
internal/rules/google/storage/bucket_encryption_customer_test.go
pkg/providers/google/storage/storage.go

As discussed with @liamg in the tfsec repo this PR is for issue #914 
Resolves #914

feat: add gcp bucket customer-managed key check

---

.github/workflows/release.yaml

The flag `--manifest-config` has changed to `--config`

chore: fix oras push

---

.github/workflows/outdated-api-update.yaml
Makefile
scripts/udpate_dynamic_policy.sh

chore: cronjob for updating outdated-api policy

---

.github/workflows/outdated-api-update.yaml

chore: add contents write permission for outdated-api update workflow

---

.github/workflows/outdated-api-update.yaml

chore: add branch protection setting

---

.github/workflows/outdated-api-update.yaml

chore: opa format write

---

internal/rules/kubernetes/policies/dynamic/outdated_api.rego

set outdated-api rego policy return result
Related #925

fix: set outdated-api rego policy return result

---

pkg/rego/convert/anonymous.go
pkg/rego/convert/slice_test.go
pkg/rego/convert/struct.go
pkg/scanners/terraform/scanner_test.go

See https://github.com/aquasecurity/tfsec/issues/1901

fix: Ensure rego input is properly filled for nested slices

---

pkg/state/merge.go
pkg/state/merge_test.go
pkg/state/state.go

feat: Add state.Merge() for merging two states

---

.github/workflows/verify-schema.yml
Makefile
cmd/schema/main.go
pkg/rego/schemas/builder.go
pkg/rego/schemas/cloud.json
pkg/types/time.go

build: Ensure schema is up-to-date

---

pkg/scanners/azure/functions/utc_now.go
pkg/scanners/azure/functions/utc_now_test.go

feat: add test for utcnow function

---

pkg/detection/detect.go
pkg/scan/code.go
pkg/scanners/azure/arm/scanner.go
pkg/scanners/azure/deployment.go
pkg/scanners/azure/functions/deployment.go
pkg/scanners/universal/scanner.go

- feat: update the universal scanner to include ARM

feat: update universal scanner 

---

pkg/rego/load.go
pkg/scanners/kubernetes/scanner_test.go
pkg/scanners/rbac/scanner_test.go
test/docker_test.go

feat: Flag both policies and libraries for embedding.

---

internal/adapters/terraform/azure/storage/adapt.go

fix: Fix for panic in azure network rule adaptation

---

avd_docs/aws/msk/AVD-AWS-0179/CloudFormation.md
avd_docs/aws/msk/AVD-AWS-0179/Terraform.md
avd_docs/aws/msk/AVD-AWS-0179/docs.md
internal/adapters/cloud/aws/msk/adapt.go
internal/adapters/cloudformation/aws/msk/cluster.go
internal/adapters/terraform/aws/msk/adapt.go
internal/adapters/terraform/aws/msk/adapt_test.go
internal/rules/aws/msk/enable_at_rest_encryption.cf.go
internal/rules/aws/msk/enable_at_rest_encryption.go
internal/rules/aws/msk/enable_at_rest_encryption.tf.go
internal/rules/aws/msk/enable_at_rest_encryption_test.go
pkg/providers/aws/msk/msk.go
pkg/rego/schemas/cloud.json

feat(aws): add msk encryption at rest check

---

internal/rules/policies/kubernetes/policies/dynamic/outdated_api.rego

change outdated api severity to low

chore: change outdated api severity to low

---

internal/specs/compliance/nsa-1.0.yaml
internal/specs/testdata/nsa-1.0.yaml

update nsa spec tag checks as manual
Close: #1041

chore: update nsa spec tag checks as manual

---

avd_docs/kubernetes/general/AVD-KSV-01010/docs.md
avd_docs/kubernetes/general/AVD-KSV-0108/docs.md
avd_docs/kubernetes/general/AVD-KSV-0109/docs.md

I believe the docs here were manually added. We need to figure out a way to get the impact from Rego rules (today they don't have them).

docs(avd): Update docs

---

internal/adapters/cloud/aws/s3/s3.go
internal/adapters/cloud/aws/s3/s3_test.go

Resolves: https://github.com/aquasecurity/defsec/issues/1067

fix: bucket encryption is enabled if SSEAlgorithm is specified

---

avd_docs/dockerfile/general/AVD-DS-0025/docs.md
internal/rules/policies/docker/policies/missing_apk_no_cache.rego
internal/rules/policies/docker/policies/missing_apk_no_cache_test.rego

I'm trying to integrate [Dockle](https://github.com/goodwithtech/dockle) into Trivy. This PR adds a new check defsec is currently missing.
https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#dkl-di-0004

feat(dockerfile): add a new check about "apk add --no-cache"

---

avd_docs/dockerfile/general/AVD-DS-0026/docs.md
internal/rules/policies/docker/lib/docker.rego
internal/rules/policies/docker/policies/no_healthcheck_instruction.rego
internal/rules/policies/docker/policies/no_healthcheck_instruction_test.rego

Similar to https://github.com/aquasecurity/defsec/pull/1139. You will find this check in the CIS Benchmark.
>3. Define HEALTHCHECK instructions for the container
https://www.aquasec.com/cloud-native-academy/docker-container/docker-cis-benchmark/#Container-Images-and-Build-File-Configuration

feat(dockerfile): add healthcheck check

---

internal/rules/aws/ec2/no_excessive_port_access.cf.go
internal/rules/aws/ec2/no_excessive_port_access.go
internal/rules/aws/ec2/no_excessive_port_access.tf.go
internal/rules/aws/ec2/no_excessive_port_access_test.go

Addresses: https://github.com/aquasecurity/trivy/issues/3283

fix(rules) updated logic for ec2 nacl rule

---

pkg/rego/embed.go
pkg/rego/embed_test.go
pkg/rego/load.go
pkg/rego/metadata.go
pkg/rego/scanner.go
pkg/rego/scanner_test.go
pkg/scanners/dockerfile/scanner_test.go

Addresses: https://github.com/aquasecurity/trivy/issues/3439

feat(schema): Add ability to provide schema

---

internal/specs/compliance/docker-cis.yaml

fix(compliance): remove unneeded hyphen

---

go.mod
go.sum
pkg/scanners/azure/functions/utc_now_test.go

fix(tests): Use UTC timestamps for testing

---

cmd/defsec/aws.go
cmd/defsec/fs.go
pkg/rego/load.go
pkg/rego/scanner.go
pkg/rego/scanner_test.go
pkg/scanners/azure/arm/scanner.go
pkg/scanners/cloud/aws/scanner.go
pkg/scanners/cloudformation/scanner.go
pkg/scanners/dockerfile/scanner.go
pkg/scanners/helm/scanner.go
pkg/scanners/helm/test/scanner_test.go
pkg/scanners/json/scanner.go
pkg/scanners/kubernetes/scanner.go
pkg/scanners/kubernetes/scanner_test.go
pkg/scanners/options/scanner.go
pkg/scanners/terraform/scanner.go
pkg/scanners/toml/scanner.go
pkg/scanners/yaml/scanner.go
test/docker_test.go
test/kubernetes_test.go

Will bring this back later.
This reverts commit 97ff1b45f3381eb77b6e6f9bf4c1a9b028bbe24d.

Revert "feat(scanner): Break out options for enabling libs and policies (#1280)"

---

pkg/rego/load.go
pkg/rego/load_test.go
pkg/rego/scanner.go
pkg/rego/scanner_test.go
pkg/rego/testdata/policies/invalid.rego
pkg/rego/testdata/policies/valid.rego
pkg/scanners/azure/arm/scanner.go
pkg/scanners/cloud/aws/scanner.go
pkg/scanners/cloudformation/scanner.go
pkg/scanners/dockerfile/scanner.go
pkg/scanners/dockerfile/scanner_test.go
pkg/scanners/helm/scanner.go
pkg/scanners/json/scanner.go
pkg/scanners/kubernetes/scanner.go
pkg/scanners/options/scanner.go
pkg/scanners/terraform/scanner.go
pkg/scanners/toml/scanner.go
pkg/scanners/yaml/scanner.go

Fixes: https://github.com/aquasecurity/trivy/issues/4183

feat(rego): Retry if some policies are broken

---

internal/adapters/terraform/azure/storage/adapt.go
rules/cloud/policies/azure/storage/use_secure_tls_policy.tf.go
rules/cloud/policies/azure/storage/use_secure_tls_policy_test.go

Fixes: https://github.com/aquasecurity/trivy/issues/4461
Ref: https://registry.terraform.io/providers/hashicorp/azurerm/2.48.0/docs/resources/storage_account

fix(azure): Update `min_tls_version` for avd-azu-0011

---

pkg/scanners/cloud/aws/scanner.go
pkg/scanners/cloud/aws/scanner_test.go

Added the test case to pass config data settings to rego rule

added logic to pass config data setting to rego rule

---

internal/adapters/cloud/aws/rds/rds.go

Fixes: https://github.com/aquasecurity/trivy/issues/4628

fix(cloud): Fix KMSKeyID check

---

CONTRIBUTING.md
Makefile

Fixed paths to policies in the doc

docs: fix the path to `policies`

---

pkg/scanners/terraform/scanner_test.go

See https://github.com/aquasecurity/trivy/issues/4618

test(terraform): add a test for the skip downloaded option

---

cmd/defsec/aws.go
cmd/defsec/fs.go
pkg/rego/load.go
pkg/rego/scanner.go
pkg/rego/scanner_test.go
pkg/scanners/azure/arm/scanner.go
pkg/scanners/cloud/aws/scanner.go
pkg/scanners/cloudformation/scanner.go
pkg/scanners/dockerfile/scanner.go
pkg/scanners/helm/scanner.go
pkg/scanners/helm/test/scanner_test.go
pkg/scanners/json/scanner.go
pkg/scanners/kubernetes/scanner.go
pkg/scanners/kubernetes/scanner_test.go
pkg/scanners/options/scanner.go
pkg/scanners/terraform/scanner.go
pkg/scanners/terraformplan/scanner.go
pkg/scanners/toml/scanner.go
pkg/scanners/yaml/scanner.go
test/docker_test.go
test/kubernetes_test.go

This reverts commit 63a8b4f763722bec6af8953684d04265e5622649.

Revert "Revert "feat(scanner): Break out options for enabling libs and policies (#1280)" (#1298)"

---

internal/adapters/terraform/azure/keyvault/adapt.go
internal/adapters/terraform/azure/keyvault/adapt_test.go

Fixes https://github.com/aquasecurity/defsec/issues/1024

fix(terraform): check that the expiration_date is string

---

pkg/scanners/cloudformation/parser/property_helpers.go
pkg/scanners/cloudformation/parser/property_helpers_test.go

See https://github.com/aquasecurity/trivy/issues/4832

fix(cloudformation): evaluate the value for a property when comparing

---

internal/adapters/terraform/aws/s3/bucket.go
internal/adapters/terraform/aws/s3/bucket_test.go

Closes https://github.com/aquasecurity/defsec/issues/468

fix(cloudformation): s3 object_lock_configuration sets versioning to true

---

pkg/scanners/kubernetes/scanner.go
pkg/scanners/kubernetes/scanner_test.go

chore(k8s): Fix a flaky test

---

pkg/rego/embed.go
pkg/rego/load.go
pkg/rego/load_test.go

Fixes: https://github.com/aquasecurity/trivy/issues/4924

feat(rego): Skip dotfiles

---

internal/adapters/terraform/aws/ec2/vpc.go
internal/adapters/terraform/aws/ec2/vpc_test.go

See https://github.com/aquasecurity/trivy/issues/4963

fix(terraform): improve VPC adapt

---

pkg/detection/detect.go
pkg/detection/detect_test.go

See https://github.com/aquasecurity/trivy/issues/4978

fix(terraform): improve detection of terraform files

---

internal/adapters/terraform/google/gke/adapt.go
internal/adapters/terraform/google/gke/adapt_test.go
pkg/providers/google/gke/gke.go
pkg/rego/schemas/cloud.json
rules/cloud/policies/google/gke/enable_network_policy.go
rules/cloud/policies/google/gke/enable_network_policy_test.go

See https://github.com/aquasecurity/trivy/issues/4961

fix(terraform): do not check network policy if enable_autopilot is true

---

avd_docs/aws/rds/AVD-AWS-0344/Terraform.md
avd_docs/aws/rds/AVD-AWS-0344/docs.md
internal/adapters/cloud/aws/rds/rds.go
internal/adapters/cloudformation/aws/rds/cluster.go
internal/adapters/terraform/aws/rds/adapt.go
internal/adapters/terraform/aws/rds/adapt_test.go
pkg/providers/aws/rds/rds.go
pkg/rego/schemas/cloud.json
rules/cloud/policies/aws/rds/disable_cluster_skip_final_snapshot.rego
rules/cloud/policies/aws/rds/disable_cluster_skip_final_snapshot_test.rego

related to https://github.com/aquasecurity/trivy/issues/5147

feat: Add support for `skip_final_snapshot`

---

pkg/terraform/context/context.go
pkg/terraform/context/context_test.go

See https://github.com/aquasecurity/trivy/issues/5001

fix(terraform): fix merging of context variables

---

pkg/providers/aws/aws.go
pkg/providers/aws/provider.go
pkg/terraform/attribute.go

See: https://github.com/aquasecurity/trivy/issues/5459
Ref:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/provider/provider.go

feat(terraform): add support for AWS provider block

---

pkg/providers/aws/aws.go

See https://github.com/aquasecurity/trivy-iac/pull/50#issuecomment-1811667401

refactor: rename providers to meta

---

pkg/terraform/context/context.go
pkg/terraform/context/context_test.go

See https://github.com/aquasecurity/trivy/issues/5752

feat(terraform): add a method to replace the value in the context

---

pkg/providers/google/gke/gke.go

See https://github.com/aquasecurity/trivy/issues/5012

feat(gke): datapath provider support for the cluster

---

pkg/terraform/presets.go

See https://github.com/aquasecurity/trivy/issues/5089

feat(terraform): fill in the arn attribute for bucket
