aquasecurity/defsec

provider/aws/dynamodb/dynamodb.go, rules/aws/dynamodb/table_customer_key.go
Old logic in tfsec checks whether the kms key attribute explicitly uses the default value. This check is missing in the defsec equivalent. 
See [tfsec check](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/aws/dynamodb/table_customer_key_rule.go#L88) and [Terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#kms_key_arn)
=> AWS DynamoDB check for default KMS key

rules/aws/documentdb/enable_log_export.go
Old [tfsec logic](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/aws/documentdb/enable_log_export_rule.go#L50) checks if either audit or profiler Cloudwatch log exports are present. Defsec equivalent checks and alerts for each separately. This PR maps the old logic.
=> AWS DocDB check either audit or profiler presence

rules/aws/kms/auto_rotate_keys.go
In the [old logic](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/aws/kms/auto_rotate_keys_rule.go#L34) in tfsec the `enable_key_rotation` attribute is checked only when the `key_usage` attribute **doesn't** equal `SIGN_VERIFY`. In defsec however, the opposite is done.
=> AWS KMS update key usage check

rules/aws/eks/no_public_cluster_access_to_cidr.go
In the [old tfsec logic ](https://github.com/aquasecurity/tfsec/blob/master/internal/app/tfsec/rules/aws/eks/no_public_cluster_access_to_cidr_rule.go#L52) CIDRs are checked only when the public access attribute is enabled. This bit is added now in defsec.
=> AWS EKS only check CIDRs when public access is enabled

rules/azure/database/secure_tls_policy.go
Removed min TLS check for MariaDB servers since apparently Terraform doesn't support it (see [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/7899)) 
Added the check for the other servers.
=> Azure Database check for min TLS version

provider/aws/vpc/vpc.go, rules/aws/vpc/add_description_to_security_group.go, rules/aws/vpc/no_excessive_port_access.go
Add check for default value on security group.
Network ACL rule protocol can also be a string (see [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl_rule)) so change `Protocol` field in struct.
Add check for string version of default value (`"all"`)
=> AWS VPC check default desc & make protocol string

avd_docs/digitalocean/compute/AVD-DIG-0006/Terraform.md, avd_docs/digitalocean/compute/AVD-DIG-0006/docs.md, provider/digitalocean/compute/compute.go, rules/digitalocean/compute/auto_upgrade_no_maintenance_policy.go, rules/digitalocean/compute/auto_upgrade_no_maintenance_policy.tf.go
Again, I'm not really sure about tests, and if `tfsec` is just the place to add this stuff. It feels a bit weird adding code without tests :man_shrugging:
=> Add check for Digital Ocean's Kubernetes auto_upgrade option.

parsers/terraform/parser/parser.go
Relates to https://github.com/aquasecurity/tfsec/issues/1495
=> fix: Ensure files are always parsed in the same order

.github/dependabot.yml
The file is just copied from tfsec. The `github-actions` and `docker` section are removed, as I don't think they're relevant in this repository.
=> chore: Add support for automatic PRs from dependabot

parsers/terraform/parser/parser.go, parsers/terraform/parser/resolvers/registry.go, parsers/terraform/parser/resolvers/remote.go, scanners/terraform/scanner.go
```
timings
──────────────────────────────────────────
disk i/o             165.732µs
parsing              6.891576905s
adaptation           80.161µs
checks               8.628285ms
total                6.900451083s
counts
──────────────────────────────────────────
modules downloaded   1
modules processed    6
blocks processsed    175
files read           16
results
──────────────────────────────────────────
passed               1
ignored              0
critical             0
high                 1
medium               1
low                  1
1 passed, 3 potential problem(s) detected.
```
Signed-off-by: Owen Rumney <owen@owenrumney.co.uk>
=> feat: add download count for the modules in the stats

pkg/rego/load.go, pkg/rego/scanner_test.go, pkg/scanners/cloudformation/scanner.go, pkg/scanners/dockerfile/scanner.go, pkg/scanners/kubernetes/option.go, pkg/scanners/kubernetes/scanner.go, pkg/scanners/kubernetes/scanner_test.go, pkg/scanners/terraform/scanner.go
Adds the `OptionWithPolicyReaders` option to the k8s scanner to allow rego policies to be dynamically loaded from one or more `io.Reader` interfaces:
```go
results, err := NewScanner(OptionWithPolicyReaders(strings.NewReader(`package defsec
deny[msg] {
msg = "fail"
}
`))).ScanReader(context.TODO(), "k8s.yaml", strings.NewReader(`
apiVersion: v1
kind: Pod
metadata: 
name: hello-cpu-limit
spec: 
containers: 
- command: ["sh", "-c", "echo 'Hello' && sleep 1h"]
image: busybox
name: hello
`))
```
=> feat: Add OptionWithPolicyReaders option to kubernetes scanner

pkg/rego/scanner.go, pkg/rego/scanner_test.go
=> fix(rego): Add filenames to passed results during rego checks

pkg/rego/exceptions.go, pkg/rego/option.go, pkg/rego/result.go, pkg/rego/scanner.go, pkg/rego/scanner_test.go, pkg/scan/result.go, pkg/scanners/cloudformation/option.go, pkg/scanners/dockerfile/option.go, pkg/scanners/json/option.go, pkg/scanners/kubernetes/option.go, pkg/scanners/terraform/options.go, pkg/scanners/toml/option.go, pkg/scanners/universal/options.go, pkg/scanners/yaml/option.go
Adds the `OptionWithPerResultTracing` rego scanner option. 
Mainly for compatibility with fanal/trivy.
This allows a consumer to gather rego traces on a per-result basis. When scans are run file-by-file, the scanner will attach traces to results found that are associated with the rule that detected the result, and the individual scan target (file). This means traces are easier to search for particular areas of interest.
=> feat: Add per-result tracing option to rego scanning

pkg/scanners/terraform/parser/load_blocks.go, pkg/scanners/terraform/parser/parser.go
Fixes [1670 issue in tfsec](https://github.com/aquasecurity/tfsec/issues/1670).
The comparison between a parsed ignore entry and a detected issue is done by filenames reported by `Range` objects in the issue and the ignore. The filenames contain the module path (as `sourcePrefix`) and relative path to the source file. Since the detected issue's `Range` had an empty string as module path, the comparison always failed for downloaded modules (as local modules had an empty string as module source).
=> fix(terraform): set module source in parsed ignores

go.mod, go.sum, integration/go.mod
[defsec](https://github.com/aquasecurity/defsec) contains CVE-2022-27191. 
this PR updates `x/crypto` for fix it.
before:
```sh
$ trivy fs .
2022-04-22T18:53:02.304+0600    INFO    Number of language-specific files: 2
2022-04-22T18:53:02.304+0600    INFO    Detecting gomod vulnerabilities...
go.mod (gomod)
==============
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------------------+------------------+----------+-----------------------------------+-----------------------------------+---------------------------------------+
|       LIBRARY       | VULNERABILITY ID | SEVERITY |         INSTALLED VERSION         |           FIXED VERSION           |                 TITLE                 |
+---------------------+------------------+----------+----------------------------- …
```
=> chore(deps): update x/crypto for fix CVE-2022-27191

internal/adapters/terraform/google/dns/adapt.go, internal/adapters/terraform/google/dns/adapt_test.go, internal/rules/google/dns/enable_dnssec.go, internal/rules/google/dns/enable_dnssec_test.go, pkg/providers/google/dns/dns.go
=> fix(rule): GCP dnssec not applicable for private zones

internal/adapters/terraform/aws/lambda/adapt.go, internal/adapters/terraform/aws/lambda/adapt_test.go
test: add tests for aws lambda tf adapters
fix: assign permissions to functions they belong to
resolves #528
=> test: add tests for aws lambda tf adapters

internal/rules/embed.go, internal/rules/embed_test.go, pkg/rego/embed.go, pkg/rego/load.go, pkg/scanners/cloudformation/scanner.go, pkg/scanners/dockerfile/scanner.go, pkg/scanners/json/scanner.go, pkg/scanners/terraform/options.go, pkg/scanners/terraform/scanner.go, pkg/scanners/terraform/scanner_test.go, pkg/scanners/toml/scanner.go, pkg/scanners/yaml/scanner.go
Allows embedded rego libraries to be optionally loaded even when embedded policies are not.
(This will require a small tfsec update.)
=> feat: Adds configurable loading of embedded libraries

pkg/rego/scanner.go, pkg/scanners/cloudformation/scanner.go, pkg/scanners/dockerfile/scanner.go, pkg/scanners/json/scanner.go, pkg/scanners/kubernetes/scanner.go, pkg/scanners/options/scanner.go, pkg/scanners/terraform/scanner.go, pkg/scanners/toml/scanner.go, pkg/scanners/yaml/scanner.go
Useful when you are scanning a different filesystem to the one your custom rego policies live on
=> feat: Add option to load policies from any given filesystem

internal/adapters/terraform/aws/rds/adapt.go, internal/adapters/terraform/aws/rds/adapt_test.go
resolves #550 
minor changes:
- `cluster_identifier`: full name of referenced block when attribute is reference
- `backup_retention_period` in `aws_rds_cluster` defaults to 1 ([docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#backup_retention_period))
- `replicate_source_db` -> `replication_source_identifier` in `aws_rds_cluster` ([docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#replication_source_identifier))
=> test: add tests for aws rds tf adapters

pkg/terraform/ignore.go, pkg/terraform/modules.go
Ignores for a foreach using ignore range and returning first derived block, not the correct one
Resolves aquasecurity/tfsec#1693
=> fix: Paramter ignores returning only the first matching block

internal/rules/kubernetes/policies/advanced/protecting_pod_service_account_tokens.rego
Changes:
* Remove duplicate `has_key` definition
* Use imported `utils.has_key`
=> refactor: Remove extraneous has_key definition

pkg/scanners/terraform/parser/resolvers/cache.go, pkg/scanners/terraform/parser/resolvers/remote.go
This fixes a few issues with the cache directory:
- The cache dir is no longer created until/unless it is needed (e.g. no longer created when `tfsec --help` is run etc.)
- Cache directory is now named `.aqua` to avoid confusion when `.tfsec` was being created in Trivy.
- Project directory is no longer tainted by the cache dir, causing issues in CI/docker etc.
=> fix: Issues with cache directory

pkg/scanners/terraform/parser/parser_test.go, pkg/scanners/terraform/parser/resolvers/cache.go, pkg/scanners/terraform/parser/resolvers/registry.go
Terraform modules can now be retrieved from private registries.
The only authentication mechanism currently supported is environment variable. See the [Terraform docs](https://www.terraform.io/cli/config/config-file#environment-variable-credentials) for more info on using env vars for authentication.
=> feat: Add support for private/non-default terraform registries

pkg/scanners/helm/parser/parser.go, pkg/scanners/helm/test/scanner_test.go, pkg/scanners/helm/test/testdata/templated-name/Chart.yaml
=> fix: Handle helm charts with templated names

internal/rules/rbac/policies/allowing_create_role_binding_and_associate_privileged_clusterrole.rego
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
`ruleA.apiGroups[_] == "rbac.authorization.k8s.io"` was check twice.
=> refactor: remove duplicate check

pkg/scanners/terraform/executor/statistics.go
Proposal: add formats json and markdown to statistics output
Why: https://github.com/aquasecurity/tfsec/issues/1790
=> feat: Add json and markdown format to --run-statistics

pkg/scanners/helm/parser/parser.go, pkg/scanners/helm/test/parser_test.go, pkg/scanners/helm/test/testdata/numberName/Chart.yaml
Related to https://github.com/aquasecurity/trivy#2459
=> Fix: handle integers for Chart name in Helm parsing

internal/adapters/terraform/google/iam/adapt_test.go, internal/adapters/terraform/google/iam/org_iam.go, internal/adapters/terraform/google/iam/project_iam.go, internal/adapters/terraform/google/iam/project_iam_test.go
additional changes: 
prevent `google_folder_iam_binding` and `google_folder_iam_member` from creating new organizations when their folder is present 
resolves #656
=> test: add tests for google iam tf adapters

internal/rules/register.go, internal/rules/register_test.go, pkg/framework/frameworks.go, pkg/rego/embed_test.go, pkg/rules/providers.go, pkg/rules/register.go, pkg/scan/rule.go, pkg/scanners/cloudformation/scanner.go, test/performance_test.go, test/rules_test.go
Backward compatible.
All rules are registered to the `default` framework by default. Specifying anything in the list of frameworks for a rule will cause it to be removed from the `default` framework unless `default` is explicitly specified in the list.
Rules can be requested for zero or more frameworks. Rules are returned which exist in any of the the supplied frameworks. If no frameworks are requested, rules for the `default` framework will be returned.
=> feat: Add framework classification capability for rules

pkg/detection/detect.go, pkg/detection/detect_test.go
Signed-off-by: Jose Donizetti <jdbjunior@gmail.com>
Add support to kubernetes configmap detection. Instead of testing specifically for ConfigMap, I opted to only test for "apiVersion", "kind", "metadata" to detect if a yaml is k8s or not, though I'm it is ignoring rbac because it has its own scanner. This means, others resources would also be detected as K8S, like secrets, endpoints, endpointslices etc, which I think it is okay because they are k8s objects. So, actually what this PR does is to stop detecting only workloads. 
Let me know what you think please. We want trivy-operator to be able to report on ConfigMaps.
=> fix: add configmap support to k8s scanner

pkg/scanners/terraform/executor/executor.go, pkg/scanners/terraform/executor/option.go, pkg/scanners/terraform/options.go
This is intended for adding `exclude-ignores` flag and --config-file attribute.
In some cases, we want to enforce some rules and remove the ability to `#tfsec:ignore`
Follow up PR for tfsec:
https://github.com/aquasecurity/tfsec/pull/1839
=> feat: Add exclude-ignores flag and --config-file attribute

internal/rules/docker/policies/workdir_path_not_absolute.rego, internal/rules/docker/policies/workdir_path_not_absolute_test.rego
Relates to https://github.com/aquasecurity/trivy/issues/2622
=> fix(rego): Allow quotes in working directories for Dockerfiles

pkg/scanners/helm/scanner.go, pkg/scanners/terraform/executor/executor.go, test/ignore_test.go
Contributes towards https://github.com/aquasecurity/tfsec/issues/1842
=> fix: Add the aliases into the ignores to support moved rules

pkg/scanners/terraform/parser/parser.go
=> fix: apply options to submodule parsers

internal/adapters/terraform/azure/storage/adapt.go, internal/rules/azure/storage/queue_services_logging_enabled.go, internal/rules/azure/storage/queue_services_logging_enabled.tf.go, internal/rules/azure/storage/queue_services_logging_enabled_test.go, pkg/providers/azure/storage/storage.go
=> fix(terraform): Fix queue logging of azure storage account being detected when no queues are used

avd_docs/github/branch_protections/AVD-GIT-0004/Terraform.md, avd_docs/github/branch_protections/AVD-GIT-0004/docs.md, internal/adapters/terraform/github/adapt.go, internal/adapters/terraform/github/branch_protections/adapt.go, internal/adapters/terraform/github/branch_protections/adapt_test.go, internal/rules/github/branch_protections/require_signed_commits.go, internal/rules/github/branch_protections/require_signed_commits.tf.go, internal/rules/github/branch_protections/require_signed_commits_test.go, pkg/providers/github/branch_protections.go, pkg/providers/github/github.go, pkg/rules/rules.go
Fixes #876.
Port over https://github.com/aquasecurity/tfsec/pull/1101 to defsec.
=> feat: GitHub branch protection should require signed commits

pkg/formatters/junit.go, pkg/formatters/junit_test.go
Previously all not passed scan results were treated as a failure by the
JUnit formatter. This was a problem for e.g. tfsec, since with a JUnit
result viewer there was no way to distinguish between ignored tests and
actually failed ones.
Now "ignored" scan results are marked as "skipped".
Additionally, a test for passed scans has been added as well. It already
worked as intended, but so far we had no test to ensure this.
=> feat: distinguish failed and ignored for JUnit (#719)

pkg/formatters/checkstyle.go, pkg/formatters/csv.go, pkg/formatters/formatter.go, pkg/formatters/json.go, pkg/formatters/junit.go, pkg/formatters/sarif.go, pkg/scan/result.go, pkg/types/metadata.go
=> fix(sarif): Fix SARIF URIs to always be local to project

avd_docs/aws/ec2/AVD-AWS-0164/CloudFormation.md, avd_docs/aws/ec2/AVD-AWS-0164/Terraform.md, avd_docs/aws/ec2/AVD-AWS-0164/docs.md, internal/adapters/cloudformation/aws/ec2/ec2.go, internal/adapters/cloudformation/aws/ec2/subnet.go, internal/adapters/terraform/aws/ec2/adapt.go, internal/adapters/terraform/aws/ec2/subnet.go, internal/adapters/terraform/aws/ec2/subnet_test.go, internal/rules/aws/ec2/no_public_ip_subnet.cf.go, internal/rules/aws/ec2/no_public_ip_subnet.go, internal/rules/aws/ec2/no_public_ip_subnet.tf.go, internal/rules/aws/ec2/no_public_ip_subnet_test.go, pkg/providers/aws/ec2/ec2.go, pkg/providers/aws/ec2/subnet.go
Fixes #875.
`aws_subnet`: `map_public_ip_on_launch` should be `false`
=> feat: Add check for ensuring subnets don't provide public IPs by default

avd_docs/aws/iam/AVD-AWS-0165/docs.md, avd_docs/aws/iam/AVD-AWS-0166/docs.md, avd_docs/aws/iam/AVD-AWS-0167/docs.md, avd_docs/aws/iam/AVD-AWS-0168/docs.md, avd_docs/aws/iam/AVD-AWS-0169/docs.md, avd_docs/aws/s3/AVD-AWS-0170/docs.md, avd_docs/aws/s3/AVD-AWS-0171/docs.md, avd_docs/aws/s3/AVD-AWS-0172/docs.md, internal/adapters/cloud/aws/cloudtrail/adapt.go, internal/adapters/cloud/aws/s3/s3.go, internal/adapters/cloudformation/aws/s3/bucket.go, internal/adapters/terraform/aws/cloudtrail/adapt.go, internal/adapters/terraform/aws/s3/adapt_test.go, internal/adapters/terraform/aws/s3/bucket.go, internal/adapters/terraform/google/iam/project_iam_test.go, internal/rules/aws/s3/enable_object_read_logging.go, internal/rules/aws/s3/enable_object_read_logging.tf.go, internal/rules/aws/s3/enable_object_read_logging_test.go, internal/rules/aws/s3/enable_object_write_logging.go, internal/rules/aws/s3/enable_object_write_logging.tf.go, internal/rules/aws/s3/enable_object_write_logging_test.go, internal/rules/aws/s3/require_mfa_delete.go, internal/rules/aws/s3/require_mfa_delete.tf.go, internal/rules/aws/s3/require_mfa_delete_test.go, pkg/providers/aws/cloudtrail/cloudtrail.go, pkg/providers/aws/s3/bucket.go, pkg/scanners/cloudformation/scanner.go, pkg/scanners/terraform/scanner.go, test/rules_test.go
Resolves #867 
Resolves #868 
Resolves #864
=> feat: Add s3 rules for CIS AWS 1.4 

internal/rules/aws/iam/no_policy_wildcards.go
See https://github.com/aquasecurity/defsec/issues/906#issuecomment-1252095523
=> fix: Readd policy wildcards rule to default framework

pkg/terraform/attribute.go
=> feat: add OnlyContains helper function

pkg/formatters/json.go, pkg/formatters/json_test.go
While developing a vim plugin, I noticed that when I run `tfsec` with the `--format json` option, if there is no lint error, it returns the following response.
```json
{ "results": null }
```
Although `null` is valid value in the JSON schema, it seems more appropriate to return an empty array so that we can handle the output more easily.
* use empty array instead of null when there's no warnings
* add test to check JSON formatter handles empty results
=> fix: return empty array with no warnings in --format json

avd_docs/aws/rds/AVD-AWS-0177/docs.md, internal/adapters/cloud/aws/rds/rds.go, internal/adapters/cloudformation/aws/rds/instance.go, internal/adapters/terraform/aws/rds/adapt.go, internal/rules/policies/cloud/policies/aws/rds/enable_deletion_protection.rego, internal/rules/policies/cloud/policies/aws/rds/enable_deletion_protection_test.rego, pkg/providers/aws/rds/rds.go, pkg/rego/schemas/cloud.json
This ports the check from https://github.com/aquasecurity/cloudsploit/blob/master/plugins/aws/rds/rdsDeletionProtectionEnabled.js
=> feat: Port cloudsploit rule 'RDS Deletion Protection Enabled' to rego

pkg/rego/result.go, pkg/scanners/kubernetes/parser/manifest_node.go, pkg/scanners/kubernetes/parser/parser.go, pkg/scanners/kubernetes/scanner_test.go, pkg/scanners/rbac/scanner_test.go
This pr fixes a mismatch in the lines when a k8s multi manifest file is parsed.
See https://github.com/aquasecurity/trivy/issues/2965
=> fix: wrong lines in multi manifest k8s files

.github/CODEOWNERS, avd_docs/kubernetes/general/AVD-KSV-01010/docs.md, avd_docs/kubernetes/general/AVD-KSV-0108/docs.md, avd_docs/kubernetes/general/AVD-KSV-0109/docs.md, internal/rules/policies/kubernetes/policies/aquacommercial/configMap_with_secrets.rego, internal/rules/policies/kubernetes/policies/aquacommercial/configMap_with_secrets_test.rego, internal/rules/policies/kubernetes/policies/aquacommercial/configMap_with_sensitive_test.rego, internal/rules/policies/kubernetes/policies/aquacommercial/configmap_with_sensitive.rego, internal/rules/policies/kubernetes/policies/aquacommercial/service_with_externalip.rego, internal/rules/policies/kubernetes/policies/aquacommercial/service_with_externalip_test.rego
Few rules which are present in Aqua product (which is used by Kube-enforcer) is not present in defsec. Migrating few policies to aquacommercial folder
=> Migrating the rules from Aqua commercial/Kube Enforcer into defsec

pkg/scanners/azure/functions/uri.go, pkg/scanners/azure/functions/uri_test.go
Aqua internal tools need to compile Trivy/defsec with Go 1.18. We need to backport `net/url.JoinPath`, which is introduced in Go 1.19 so defsec will be compatible with Go 1.18.
https://pkg.go.dev/net/url#JoinPath
=> Compatible with Go 1.18

internal/specs/compliance/docker-cis.yaml, internal/specs/loader_test.go
This PR adds support for CIS Docker Community Edition Benchmark.
https://www.cisecurity.org/benchmark/docker
- https://github.com/aquasecurity/defsec/pull/1141
- https://github.com/aquasecurity/defsec/pull/1139
=> feat(spec): add support for CIS Docker Community Edition Benchmark

Makefile, avd_docs/aws/rds/AVD-AWS-0082/Terraform.md, avd_docs/aws/rds/AVD-AWS-0180/CloudFormation.md, avd_docs/aws/rds/AVD-AWS-0180/Terraform.md, cmd/avd_generator/main.go, cmd/avd_generator/main_test.go, internal/rules/aws/rds/no_public_db_access.cf.go, internal/rules/aws/rds/no_public_db_access.tf.go, internal/rules/policies/cloud/policies/aws/rds/disable_public_access.rego
See this rego policy for an example: https://github.com/aquasecurity/defsec/blob/954d15e5b61a0e8a8731a5d8c3f3cf5009e235a6/internal/rules/policies/cloud/policies/aws/rds/disable_public_access.rego#L19-L22
```rego
package builtin.aws.rds.aws0180
deny[res] {
instance := input.aws.rds.instances[_]
instance.publicaccess.value
res := result.new("Instance has Public Access enabled", instance.publicaccess)
}
```
Addresses: https://github.com/aquasecurity/trivy/issues/3440
Signed-off-by: Simar <simar@linux.com
=> feat(docs): Support example annotations within rego policies

pkg/rego/load.go, pkg/rego/scanner.go, pkg/rego/store.go, pkg/scanners/azure/arm/scanner.go, pkg/scanners/cloud/aws/scanner.go, pkg/scanners/cloudformation/scanner.go, pkg/scanners/dockerfile/scanner.go, pkg/scanners/helm/scanner.go, pkg/scanners/json/scanner.go, pkg/scanners/kubernetes/scanner.go, pkg/scanners/options/scanner.go, pkg/scanners/terraform/scanner.go, pkg/scanners/toml/scanner.go, pkg/scanners/yaml/scanner.go
Add a new option to pass the data file system so that the file system can be abstract.
https://github.com/aquasecurity/trivy/pull/3578
=> feat(rego): accept fs.FS for data

pkg/formatters/sarif.go
=> fix: output correct path for nested terraform modules (SARIF)

pkg/rego/scanner.go, pkg/scanners/cloud/aws/scanner_test.go
Currently we do this check at the wrong place, it should be evaluated prior.
This should also take care of the situation where no selectors are defined at all.
=> fix(selectors): Evaluate policy when no selectors are present

avd_docs/aws/sam/AVD-AWS-0116/CloudFormation.md, internal/adapters/cloudformation/aws/sam/http_api.go, rules/cloud/policies/aws/sam/enable_http_api_access_logging.cf.go
`AWS::Serverless::HttpApi` uses `AccessLogSettings` instead of `AccessLogSetting`.
See
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-accesslogsettings
=> fix(aws/sam): fix HttpApi access logging rule

pkg/formatters/sarif_test.go
=> test: ensure SARIF doesn't print parent metadata

avd_docs/aws/elb/AVD-AWS-0047/Terraform.md, rules/cloud/policies/aws/elb/use_secure_tls_policy.go, rules/cloud/policies/aws/elb/use_secure_tls_policy.tf.go, rules/cloud/policies/aws/elb/use_secure_tls_policy_test.go
AWS has added additional ELB security policies that support TLS v1.3. Some of them should be treated as outdated/unsafe, as they enable ciphers that are effectively deprecated.
https://aws.amazon.com/about-aws/whats-new/2023/03/application-load-balancer-tls-1-3/
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
Reasoning for each addition:
* `ELBSecurityPolicy-FS-2018-06` -- supports TLS v1.0 and v1.1
* `ELBSecurityPolicy-FS-1-1-2019-08` -- supports TLS v1.1
* `ELBSecurityPolicy-TLS13-1-0-2021-06` -- supports TLS v1.0 and v1.1
* `ELBSecurityPolicy-TLS13-1-1-2021-06` -- supports TLS v1.1
* `ELBSecurityPolicy-TLS13-1-2-Ext1-2021-06` -- supports non elliptic curve cryptography cipher suites
* …
=> fix(rules): Update list of outdated ELB TLS policies

internal/adapters/terraform/azure/container/adapt.go, internal/adapters/terraform/azure/container/adapt_test.go, rules/cloud/policies/azure/container/limit_authorized_ips.tf.go
this commit fixes #3850 https://github.com/aquasecurity/trivy/issues/3850
=> api_server_authorized_ip_ranges deprecated

avd_docs/azure/storage/AVD-AZU-0011/Terraform.md, avd_docs/dockerfile/general/AVD-DS-0027/docs.md, avd_docs/google/compute/AVD-GCP-0043/Terraform.md, avd_docs/google/compute/AVD-GCP-0045/Terraform.md, rules/cloud/policies/google/compute/disk_encryption_no_plaintext_key.tf.go, rules/cloud/policies/google/compute/enable_shielded_vm_im.tf.go, rules/cloud/policies/google/compute/no_ip_forwarding.tf.go
Minor fixes for rule tf examples inside a string.
=> Minor fix: Rule tf examples

rules/kubernetes/policies/cisbenchmarks/apiserver/client_ca_file.rego, rules/kubernetes/policies/cisbenchmarks/apiserver/client_ca_file_test.rego, rules/kubernetes/policies/cisbenchmarks/apiserver/etcd_cafile.rego, rules/kubernetes/policies/cisbenchmarks/apiserver/etcd_cafile_test.rego
Now [client_ca_file.rego](https://github.com/aquasecurity/defsec/blob/master/rules/kubernetes/policies/cisbenchmarks/apiserver/client_ca_file.rego#L25) and [etcd_cafile.rego](https://github.com/aquasecurity/defsec/blob/master/rules/kubernetes/policies/cisbenchmarks/apiserver/etcd_cafile.rego#L25) checks fail when `--client-ca-file` and `--etcd-cafile` flags are set in `kube-apiserver` pod spec respectively. 
But CIS benchmark spec says that `--client-ca-file` and `--etcd-cafile` flags must be set with proper values.
This PR fixes this inaccuracy
=> Fix: `AVD-KCV-0028` and `AVD-KCV-0029` checks

rules/kubernetes/lib/kubernetes.rego, rules/kubernetes/lib/kubernetes_test.rego
Now in functions `is_apiserver`, `is_etcd`, `is_controllermananager` and `is_scheduler` regexes for first command entry are not "strict", so when there is more than one container in control plane pod with first command entries, for example, `kube-apiserver` and `kube-apiserver-healthcheck` - checks for control plane containers would be applied also for another (non control plane) container. This produces false negative check results.
In this PR I proposed solution for fixing this behavior.
=> Fix: correct search for control plane containers

pkg/scanners/terraform/parser/load_vars.go, pkg/scanners/terraform/parser/load_vars_test.go, pkg/scanners/terraform/parser/testdata/tfvars/terraform.tfvars, pkg/scanners/terraform/parser/testdata/tfvars/terraform.tfvars.json
Partially addresses: https://github.com/aquasecurity/trivy/issues/4006
Needs https://github.com/aquasecurity/trivy/pull/3991 to fully fix this.
=> fix(terraform): Use absolute path for filesystem to load tfvars

avd_docs/google/compute/AVD-GCP-0067/Terraform.md, avd_docs/google/compute/AVD-GCP-0067/docs.md, rules/cloud/policies/google/compute/enable_shielded_vm_sb.go, rules/cloud/policies/google/compute/enable_shielded_vm_sb.tf.go, rules/cloud/policies/google/compute/enable_shielded_vm_sb_test.go
Adding GCP rule for enable secure boot within shielded VM:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#enable_secure_boot
=> feat: GCP compute instance rule 'enable secure boot'

cmd/defsec/aws.go, cmd/defsec/fs.go, pkg/rego/load.go, pkg/rego/scanner.go, pkg/rego/scanner_test.go, pkg/scanners/azure/arm/scanner.go, pkg/scanners/cloud/aws/scanner.go, pkg/scanners/cloudformation/scanner.go, pkg/scanners/dockerfile/scanner.go, pkg/scanners/helm/scanner.go, pkg/scanners/helm/test/scanner_test.go, pkg/scanners/json/scanner.go, pkg/scanners/kubernetes/scanner.go, pkg/scanners/kubernetes/scanner_test.go, pkg/scanners/options/scanner.go, pkg/scanners/terraform/scanner.go, pkg/scanners/toml/scanner.go, pkg/scanners/yaml/scanner.go, test/docker_test.go, test/kubernetes_test.go
This adds the `SetUseEmbeddedLibraries` option for scanners. It is needed in cases where we only want to load libraries but not policies. 
=> feat(scanner): Break out options for enabling libs and policies

pkg/detection/detect.go, pkg/scanners/terraform/parser/load_vars.go, pkg/scanners/terraform/parser/load_vars_test.go
Fixes https://github.com/aquasecurity/trivy/issues/4006
=> feat(terraform): Support tfvars files during scans

rules/kubernetes/policies/cisbenchmarks/kubelet/kubelet_anonymous_auth_argument.rego, rules/kubernetes/policies/cisbenchmarks/kubelet/kubelet_anonymous_auth_argument_test.rego, rules/kubernetes/policies/cisbenchmarks/kubelet/kubelet_read_only_port_argument.rego, rules/kubernetes/policies/cisbenchmarks/kubelet/kubelet_read_only_port_argument_test.rego
Related https://github.com/aquasecurity/trivy-operator/issues/1181
=> fix: kubelet policies --read-only-port and --anonymous-auth

rules/docker/policies/run_using_wget_and_curl.rego
This matches the split used in `run_command_cd_instead_of_workdir.rego`
=> Improve the command splitting

avd_docs/google/iam/AVD-GCP-0068/Terraform.md, avd_docs/google/iam/AVD-GCP-0068/docs.md, internal/adapters/terraform/google/iam/adapt.go, internal/adapters/terraform/google/iam/adapt_test.go, internal/adapters/terraform/google/iam/workload_identity_pool_providers.go, pkg/providers/google/iam/iam.go, pkg/rego/schemas/cloud.json, rules/cloud/policies/google/iam/no_conditions_on_workload_identity_pool_provider.go, rules/cloud/policies/google/iam/no_conditions_on_workload_identity_pool_provider.tf.go, rules/cloud/policies/google/iam/no_conditions_on_workload_identity_pool_provider_test.go
Addresses https://github.com/aquasecurity/defsec/issues/1337
=> Add new rule: Google IAM Workload Identity Pool Provider with no conditions

pkg/scanners/terraform/parser/evaluator.go, pkg/scanners/terraform/parser/parser_test.go, pkg/terraform/schema.go, pkg/terraform/type.go
docs:
- https://github.com/hashicorp/terraform/blob/v1.5/CHANGELOG.md#150-june-12-2023
- https://developer.hashicorp.com/terraform/language/import
New `import` block was added from Terraform 1.5.0
I added type support in a form similar to `moved` block.
=> support import block for tf 1.5.0+

pkg/scanners/terraform/parser/evaluator.go, pkg/scanners/terraform/parser/parser_test.go, pkg/terraform/schema.go, pkg/terraform/type.go
As of Terraform 1.5, support has been added for `check` blocks.
https://github.com/hashicorp/terraform/blob/v1.5/CHANGELOG.md#150-june-12-2023
https://developer.hashicorp.com/terraform/language/checks
I'm adding `check` type support in a form similar to `import` block.
=> support check block for tf 1.5.0+

avd_docs/aws/iam/AVD-AWS-0342/docs.md, rules/cloud/policies/aws/iam/filter_iam_pass_role.rego, rules/cloud/policies/aws/iam/filter_iam_pass_role_test.rego
This reverts commit b5376b04a53b335467d26ab787fec669d39b0fc9.  This is revert of the Iam pass role rego policy
=> Revert "fix: Revert AVD-AWS-0342 policy (#1309)"

pkg/scanners/azure/arm/parser/armjson/parse_comment.go, pkg/scanners/azure/arm/parser/armjson/parse_number.go, pkg/scanners/azure/arm/parser/armjson/parse_string.go, pkg/scanners/azure/expressions/lex.go
Currently, in some places, when parsing ARM the resulting string is created by concatenation. Since string is a primitive type and a new string will be created each time, this is not effective. In go 1.10, was added [strings.Builder](https://pkg.go.dev/strings#Builder ), which effectively creates a string - O(n).
See https://github.com/aquasecurity/defsec/issues/1108
```shell
benchstat concat=old.txt strings.Builder=new.txt
goos: darwin
goarch: arm64
pkg: github.com/aquasecurity/defsec/pkg/scanners/azure/arm/parser/armjson
│    concat    │            strings.Builder            │
│    sec/op    │    sec/op     vs base                 │
Unmarshal_JFather-8       25.45µ ± ∞ ¹   17.54µ ± ∞ ¹        ~ (p=1.000 n=1) ²
Unmarshal_Traditional-8   4.705µ ± ∞ ¹   4.934µ ± ∞ ¹        ~ (p=1.000 n=1) …
```
=> perf(detection): use strings.Builder

pkg/scanners/cloud/aws/scanner.go
Currently we default to using `C:\` which is not correct at all times.
=> fix(windows): Use correct homedir on Windows

pkg/scanners/terraform/parser/evaluator.go, pkg/scanners/terraform/parser/parser_test.go, pkg/terraform/attribute.go
Evaluating an expression like `attr = var.some_var != null ? var.some_var : "default"` fails: `The true and false result expression must have consistent types`.
Terraform [supports null](https://developer.hashicorp.com/terraform/language/expressions/types#null) values that have no type. But defsec converts null with type [DynamicPseudoTypes](https://github.com/zclconf/go-cty/blob/7dcbae46a6f247e983efb1fa774d2bb68781a333/cty/unknown.go#L59) to `city.NilVal`, which cannot be used in conditional expressions.
See https://github.com/aquasecurity/trivy/discussions/4736
=> fix(terraform): allow nullable value for default values of vars

pkg/rego/scanner_test.go, pkg/rego/store.go
When loading custom data, if any errors occurs while parsing files on the filesystem the associated logic fails to continue.
Current behaviour makes it so that any errors, we stop processing. This is too restrictive and can be changed to rather not filter upon errors and allow the files within the `dataFS` to be processed normally.
=> fix(opa): Continue upon filter fs errors

pkg/scanners/terraform/parser/evaluator.go, pkg/scanners/terraform/parser/parser_test.go
Now the resource instance overwrites the context variables of the previous instances, which makes it impossible to use multiple instances of the same resource.
See https://github.com/aquasecurity/trivy/issues/4627
=> feat(terraform): support for multiple instances of the same resource

avd_docs/azure/container/AVD-AZU-0041/Terraform.md, rules/cloud/policies/azure/container/limit_authorized_ips.tf.go
The `api_server_authorized_ip_ranges` field is deprecated, replaced the links with `authorized_ip_range`.
See https://github.com/aquasecurity/trivy/issues/4624
Related PR:
- https://github.com/aquasecurity/defsec/pull/1254
=> fix(doc): update the links to authorized_ip_ranges

pkg/scanners/helm/options.go, pkg/scanners/helm/parser/option.go, pkg/scanners/helm/parser/parser.go, pkg/scanners/helm/test/option_test.go, pkg/scanners/helm/test/testdata/expected/options/with-api-version/templates/pdb.yaml, pkg/scanners/helm/test/testdata/with-api-version/.helmignore, pkg/scanners/helm/test/testdata/with-api-version/Chart.yaml, pkg/scanners/helm/test/testdata/with-api-version/templates/_helpers.tpl, pkg/scanners/helm/test/testdata/with-api-version/templates/pdb.yaml
This PR add an function is pass `--api-versions` to the helm command.
This resolves an issue, where trivy reports a misconfiguration because of deprecated APIVersions, but the helm chart is using `Capabilities.APIVersions.Has` to validate if the newer API Version is available. 
```yaml
apiVersion: {{ $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" | ternary "policy/v1" "policy/v1beta1" }}
kind: PodDisruptionBudget
```
`Capabilities.APIVersions.Has` does not work well, since defsec is running helm with `--dry-run --client`
=> Support define api-versions for helm scanner

rules/docker/policies/apt_get_missing_yes_flag_to_avoid_manual_input.rego, rules/docker/policies/apt_get_missing_yes_flag_to_avoid_manual_input_test.rego
Fixes https://github.com/aquasecurity/defsec/issues/1173
Dockerfile:
```Dockerfile
FROM debian:11-slim
RUN apt-get install apt-utils -y
```
```shell
AVD-DS-0029 dockerfile-general-use-apt-no-install-recommends Dockerfile:2
AVD-DS-0002 dockerfile-general-least-privilege-user Dockerfile
AVD-DS-0026 dockerfile-general-no-healthcheck Dockerfile
AVD-DS-0021 dockerfile-general-use-apt-auto-confirm Dockerfile:2
```
```shell
AVD-DS-0002 dockerfile-general-least-privilege-user Dockerfile
AVD-DS-0029 dockerfile-general-use-apt-no-install-recommends Dockerfile:2
AVD-DS-0026 dockerfile-general-no-healthcheck Dockerfile
```
=> fix(docker): check the `-y` flag after packages

pkg/scanners/cloudformation/parser/fn_ref.go, pkg/scanners/cloudformation/parser/parser.go, pkg/scanners/cloudformation/parser/parser_test.go
The context of the file was not set for the conditions, so they could not refer to the parameters.
See: https://github.com/aquasecurity/trivy/issues/3418
=> fix(cloudformation): set context for conditions

pkg/scan/flat.go, pkg/scan/result.go, pkg/scan/result_test.go
Added the `occurrences` field. Based on this field, we can display a list of occurrences in reports.
See https://github.com/aquasecurity/trivy/issues/4581
Example of json output:
```json
{
"results": [
{
"rule_id": "AVD-AWS-0107",
"long_id": "aws-ec2-no-public-ingress-sgr",
"rule_description": "An ingress security group rule allows traffic from /0.",
"rule_provider": "aws",
"rule_service": "ec2",
"impact": "Your port exposed to the internet",
"resolution": "Set a more restrictive cidr range",
"links": [
"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-rules-reference.html"
],
"description": "Security group rule allows ingress from public internet.",
"severity": "CRITICAL",
"warning": false,
"status": 0,
"resource": "module.aws-security-groups[\"db1\"]",
"occurrences": [ …
```
=> feat: add the occurrences field

pkg/scanners/cloudformation/parser/property.go, pkg/scanners/cloudformation/parser/resource_test.go
When a property is a value returned by a condition, then defsec does not evaluate it
Example:
```yaml
Resources:
Bucket:
Type: "AWS::S3::Bucket"
Properties:
VersioningConfiguration:
!If [true, { Status: Enabled }, { Status: Suspended }]
```
Output:
```bash
....
AVD-AWS-0090 aws-s3-enable-versioning test.yaml:2-6
....
```
See https://github.com/aquasecurity/trivy/issues/4844
=> fix(cloudformation): resolve property depending on conditions

pkg/scanners/azure/value.go, pkg/scanners/azure/value_test.go
The wrong type was used when converting the value to `int`.
See https://github.com/aquasecurity/trivy/issues/4792
Example to reproduce the problem:
```json
{
"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
"contentVersion": "2.0.0.0",
"apiProfile": "2019-03-01-hybrid",
"parameters": {},
"variables": {},
"functions": [],
"resources": [
{
"name": "flowlogs/sample",
"type": "Microsoft.Network/networkWatchers/flowLogs",
"apiVersion": "2020-11-01",
"location": "location",
"tags": {},
"properties": {
"targetResourceId": "targetResourceId",
"storageId": "storageId",
"enabled": true,
"retentionPolicy": {
"days": 2
},
"format": {
"type": "JSON"
}
}
}
],
"outputs": {}
}
```
=> fix(arm): use correct type casting for ints in azure scan

rules/docker/policies/apt_get_missing_no_install_recommends.rego, rules/docker/policies/apt_get_missing_no_install_recommends_test.rego
We should also check the `--no-install-recommends` flag after packages
See https://github.com/aquasecurity/trivy/issues/4462
```Dockerfile
FROM debian:11-slim
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y \
tzdata \
postgresql-10 \
--no-install-recommends && \ 
rm -rf /var/lib/apt/lists/*
```
```shell
AVD-DS-0026 dockerfile-general-no-healthcheck Dockerfile
AVD-DS-0029 dockerfile-general-use-apt-no-install-recommends Dockerfile:3-8
AVD-DS-0002 dockerfile-general-least-privilege-user Dockerfile
```
```
AVD-DS-0002 dockerfile-general-least-privilege-user Dockerfile
AVD-DS-0026 dockerfile-general-no-healthcheck Dockerfile
```
=> fix(docker): check the `--no-install-recommends` flag after packages

pkg/scanners/cloudformation/parser/fn_length.go, pkg/scanners/cloudformation/parser/fn_length_test.go, pkg/scanners/cloudformation/parser/intrinsics.go, pkg/scanners/cloudformation/parser/property_helpers.go
CloudFormation [has](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-length.html) `Length` function that returns the number of elements in the array.
See https://github.com/aquasecurity/trivy/issues/4845
=> feat(cloudformation): add support for the length function

.github/workflows/adapter-lint.yml, .github/workflows/lint.yml, .github/workflows/test-bundle.yml, .github/workflows/test-go.yml, .github/workflows/test-rego.yaml, .github/workflows/verify-schema.yml
=> chore(github): Enable merge-queues for defsec PRs

pkg/scanners/helm/test/scanner_test.go, rules/kubernetes/policies/advanced/default_namespace_should_not_be_used.rego, rules/kubernetes/policies/advanced/optional/capabilities_no_drop_at_least_one.rego, rules/kubernetes/policies/advanced/optional/manages_etc_hosts.rego, rules/kubernetes/policies/general/allowing_to_update_a_malicious_pod.rego, rules/kubernetes/policies/general/allowing_to_update_a_malicious_pod_test.rego, rules/kubernetes/policies/general/capabilities_no_drop_all.rego, rules/kubernetes/policies/general/delete_pod_logs.rego, rules/kubernetes/policies/general/get_shell_on_pod.rego, rules/kubernetes/policies/general/get_shell_on_pod_test.rego, rules/kubernetes/policies/general/manage_configmaps.rego, rules/kubernetes/policies/general/manage_kubernetes_networking.rego, rules/kubernetes/policies/general/manage_kubernetes_rbac_resources.rego, rules/kubernetes/policies/general/runs_with_GID_le_10000.rego, rules/kubernetes/policies/general/runs_with_UID_le_10000.rego, rules/kubernetes/policies/general/uses_image_tag_latest.rego, rules/kubernetes/policies/pss/baseline/10_windows_host_process.rego, rules/kubernetes/policies/pss/baseline/11_seccomp_profile_unconfined.rego, rules/kubernetes/policies/pss/baseline/11_seccomp_profile_unconfined_test.rego, rules/kubernetes/policies/pss/baseline/2_privileged.rego, rules/kubernetes/policies/pss/baseline/3_specific_capabilities_added.rego, rules/kubernetes/policies/pss/baseline/6_apparmor_policy_disabled.rego, rules/kubernetes/policies/pss/restricted/1_non_core_volume_types.rego, rules/kubernetes/policies/pss/restricted/2_can_elevate_its_own_privileges.rego, rules/kubernetes/policies/pss/restricted/5_runtime_default_seccomp_profile_not_set.rego, rules/kubernetes/policies/rolebinding/cluster_admin_role_is_only_used_where_required.rego, rules/kubernetes/policies/rolebinding/cluster_admin_role_is_only_used_where_required_test.rego
Our objective is to align the titles and logic with the commercial version.
=> Our objective is to align the titles and logic with the commercial version.

internal/adapters/cloud/aws/adapt.go
See https://github.com/aquasecurity/trivy/issues/4883
=> fix(aws): use correct signing region

.github/workflows/test-trivy.yaml
Closes https://github.com/aquasecurity/trivy/issues/4828
=> ci(test): add trivy tests

internal/adapters/cloud/aws/rds/rds.go, internal/adapters/cloudformation/aws/rds/cluster.go, internal/adapters/terraform/aws/rds/adapt.go, internal/adapters/terraform/aws/rds/adapt_test.go, pkg/providers/aws/rds/rds.go, pkg/rego/schemas/cloud.json
There is a behavior in `availability_zones` in `aws_rds_cluster` that may cause resource re-creation to be performed. An additional parameter has been added to allow inspection of this issue.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#availability_zones
=> feat(cloud): add availability zone filed for rds cluster

avd_docs/kubernetes/general/AVD-KSV-0122/docs.md, rules/kubernetes/policies/general/anonymous_user_bind.rego, rules/kubernetes/policies/general/anonymous_user_bind_test.rego
Added new rego check which checks Anonymous user access binding to rolebinding or clusterrolebinding.
The same is referred here https://blog.aquasec.com/kubernetes-exposed-one-yaml-away-from-disaster
=> Anonymous user access binding to RoleBinding and ClusterRoleBinding

pkg/terraform/attribute.go, pkg/terraform/block.go, pkg/terraform/reference.go, pkg/terraform/reference_test.go
See https://github.com/aquasecurity/trivy/issues/4983
=> fix: make operations with reference key safe

.github/actions/setup-opa/action.yaml, .github/workflows/outdated-api-update.yaml, .github/workflows/test-bundle.yml, .github/workflows/test-rego.yaml
I also took out the installation of OPA in a composite action
Close https://github.com/aquasecurity/defsec/issues/1440
=> ci: make the OPA installation more reliable

.golangci.yml
Deprecated dead code linters have been removed in https://github.com/aquasecurity/defsec/commit/deda78733569fa6a08693cdcf5ec15b89d4ae00a .
I removed them from the rules in the `golangci-lint` config
Close: https://github.com/aquasecurity/defsec/issues/1441
=> chore: remove deprecated dead code linters from the rules

avd_docs/aws/rds/AVD-AWS-0343/Terraform.md, avd_docs/aws/rds/AVD-AWS-0343/docs.md, internal/adapters/cloud/aws/rds/rds.go, internal/adapters/cloudformation/aws/rds/cluster.go, internal/adapters/terraform/aws/rds/adapt.go, internal/adapters/terraform/aws/rds/adapt_test.go, pkg/providers/aws/rds/rds.go, pkg/rego/schemas/cloud.json, rules/cloud/policies/aws/iam/filter_iam_pass_role_test.rego, rules/cloud/policies/aws/rds/enable_cluster_deletion_protection.rego, rules/cloud/policies/aws/rds/enable_cluster_deletion_protection_test.rego
Fixes https://github.com/aquasecurity/trivy/issues/5112
I want to avert some human mistakes in the RDS Cluster, but I can't detect them now.
( Now, I can only detect the RDS instance's deletionProtection. )
For example, the below codes are not working as intended.
```
deny[res] {
cluster := input.aws.rds.clusters[_]
instance := cluster.instances[_]
not instance.deletionprotection.value
res := result.new("Cluster does not have Deletion Protection enabled", instance.deletionprotection)
}
```
So, I would like to add the DeletionProtection attribute to the RDS Cluster.
=> feat(cloud): add the DeletionProtection attribute to the RDS Cluster

pkg/scanners/terraform/parser/evaluator.go, pkg/scanners/terraform/parser/parser_test.go, pkg/terraform/attribute.go, test/module_test.go
See https://github.com/aquasecurity/trivy/issues/4997
The problem was that defsec did not convert variables to the expected type, which prevented variables of type `set`, `map` or `object` from being used as an argument to [for_each](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#the-for_each-meta-argument). This PR adds conversion of input variable values to the expected [type](https://developer.hashicorp.com/terraform/language/values/variables#type-constraints). 
Also, `defsec` will now take into account the default values that the [optional](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#optional-object-type-attributes) modifier sets if the value of a variable attribute is missing:
```tf
variable "policy_rules" {
type = …
```
=> fix(terraform): convert input variables to expected type

pkg/scanners/terraform/parser/load_module.go, pkg/scanners/terraform/parser/resolvers/local.go, pkg/scanners/terraform/parser/resolvers/local_test.go, pkg/scanners/terraform/parser/resolvers/testdata/recursive/child_module/foo/foo.tf, pkg/scanners/terraform/parser/resolvers/testdata/recursive/dot_source/foo.tf
See https://github.com/aquasecurity/trivy/issues/5121
=> fix(terraform): detect recursive modules

internal/adapters/terraform/aws/s3/bucket.go, pkg/scanners/terraform/parser/parser_test.go, pkg/terraform/block.go, rules/cloud/policies/aws/s3/encryption_customer_key.go
See https://github.com/aquasecurity/trivy/issues/5080
=> fix(terraform): check if SSE configuration block is nil

internal/adapters/terraform/azure/storage/adapt.go
Fixes https://github.com/aquasecurity/trivy/issues/4981
=> fix(azure): Bump up `min_tls_value` for storage adapters

go.mod, pkg/scanners/terraform/parser/evaluator.go, pkg/scanners/terraform/scanner.go, pkg/scanners/terraform/scanner_test.go, pkg/terraform/module.go, pkg/terraform/modules.go
This PR fixes a bug when Trivy scans local modules as root modules. See https://github.com/aquasecurity/trivy/issues/4988.
Configuration example:
`main.tf`
```tf
module "main" {
source      = "./modules/s3"
versioning = "Enabled"
}
```
`modules/s3/main.tf`
```tf
variable "versioning" {
type = string
}
resource "aws_s3_bucket" "main" {
bucket = "test"
}
resource "aws_s3_bucket_versioning" "example" {
bucket = aws_s3_bucket.main.id
versioning_configuration {
status = var.versioning
}
}
```
Before:
```bash
trivy config . -f json | jq '.Results[] | .Misconfigurations | .[]?.Title'
2023-10-05T20:10:23.028+0700	INFO	Misconfiguration scanning is enabled
2023-10-05T20:10:24.956+0700	INFO	Detected config files: 3
"S3 Access block should block public ACL"
"S3 Access block should block public ACL" …
```
=> fix(terraform): do not scan local modules as root modules

pkg/terraform/module.go, pkg/terraform/modules.go
To filter non-root modules, we should only check paths of local modules.
See https://github.com/aquasecurity/trivy/issues/5414
=> fix(terraform): check if module is local

pkg/providers/google/gke/gke.go
PodSecurityPolicy has been [removed](https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs).
=> fix: remove PodSecurityPolicy field

pkg/providers/google/dns/dns.go
DefaultKeySpecs is a list https://cloud.google.com/config-connector/docs/reference/resource-docs/dns/dnsmanagedzone#schema
=> refactor(google): update DNSManagedZone resource structure

pkg/rego/scanner.go
k8s policy subtype support
- Related #https://github.com/aquasecurity/trivy/issues/5679
=> feat: k8s policy subtype support

pkg/providers/digitalocean/compute/compute.go
`redirect_http_to_https` is required for  https://github.com/aquasecurity/trivy/issues/5111
=> feat(digitalocean): support for redirect_http_to_https for load balancer

pkg/providers/aws/ec2/launch.go, pkg/terraform/presets.go
See https://github.com/aquasecurity/trivy/issues/5793
=> feat(ec2): name support for the launch template

pkg/terraform/attribute.go
The [AllReferences](https://github.com/aquasecurity/defsec/blob/4ab1fa82def6e743d722418f3db90b554622d1f9/pkg/terraform/attribute.go#L946) method of the `ssh_keys` attribute returns only 1 reference to a block, but must return 2. The attribute expression is [TupleConsExpr](https://github.com/hashicorp/hcl/blob/v2.19.1/hclsyntax/expression.go#L1035), which represents a list or set of expressions that can reference another block.  This PR fixes this and extracts references from each `TupleConsExpr` expression.
Sample config:
```tf
data "digitalocean_ssh_key" "first" {
name = "mikhalych_deploy_key"
}
data "digitalocean_ssh_key" "second" {
name = "d.lukshto-deploy-key"
}
resource "digitalocean_droplet" "this" {
image              = "ubuntu-20-04-x64"
name               = "test"
region …
```
=> fix(terraform): fix reference extraction from TupleConsExpr

pkg/providers/aws/iam/iam.go, pkg/rego/schemas/cloud.json
See https://github.com/aquasecurity/trivy/issues/5955
The `sourceprefix` field is required to check that the module is remote.
=> fix(iam): pass all document metadata fields to rego
